openapi/golem-cloud-server-oss.yaml

The generation code/script is not included here, because I am still not sure what's the best way to generate - i.e, to use script, or as part of build etc

Add open api spec for OSS cloud-server

---

openapi/golem-cloud-server-oss.yaml

golem-cloud-server-oss - openapi fix

---

golem-worker-executor-base/src/durable_host/filesystem/preopens.rs

Applied wasmtime change: https://github.com/golemcloud/wasmtime/commit/341a3abb74d955b5513fe7d5d4e3961eba68a803

Durable preopens::get-directories

---

.github/workflows/ci.yaml

parallel build of targets for docker
successful run (without publish) https://github.com/golemcloud/golem-services/actions/runs/7681364498/job/20934477766

CI docker build

---

golem-worker-executor-base/src/durable_host/filesystem/types.rs
golem-worker-executor-base/tests/wasi.rs
test-templates/build-components.sh

Also has a convenience update to the test-template build script to avoid accidentally rebuilding the swift and python wasms every time.

GOL-30 Durable read directory

---

.github/workflows/ci.yaml

Reverts golemcloud/golem-services#89

Revert "remove target cache"

---

.github/workflows/ci.yaml
.gitmodules
CONTRIBUTING.md
Cargo.toml
scripts/build-all.sh
scripts/expected-client-version.sh
scripts/generate-golem-client.sh
scripts/it.sh

Test against CLI and local binaries

integration tests

---

CONTRIBUTING.md

Tests with no docker

---

docker-compose-postgres.yaml
docker-compose-sqlite.yaml
docker-examples/docker-compose-postgres.yaml
docker-examples/docker-compose-sqlite.yaml

Fix internal port of redis

---

golem-common/src/config.rs
golem-common/src/redis.rs

add optional username and password into redis configuration

redis config - username, password

---

kube/README.md
kube/golem-chart/.helmignore
kube/golem-chart/Chart.yaml
kube/golem-chart/templates/deployment.yaml
kube/golem-chart/templates/pvc.yaml
kube/golem-chart/templates/service.yaml
kube/golem-chart/values.yaml

- template storage - persistence volume claim (in next version, support for different storage will be added: S3)
- golem-service - disabled health check - latest released version do not have health check  (changes are already in main, needs to be released)
- redis auth  - disabled  - latest released version do not have support for username and password (changes are already in main, needs to be released)

kube helm chart for golem-services

---

kube/README.md
kube/golem-chart/templates/deployment.yaml
kube/golem-chart/templates/ingress.yaml
kube/golem-chart/templates/pvc.yaml
kube/golem-chart/templates/service.yaml
kube/golem-chart/values.yaml

changes:
- added worker-bridge - not tested as we do not have published docker image yet
- added storage configuration with `pvc` (tested) and `s3` (not tested) support
- added ingress for management APIs
next steps:
- worker-bridge 
- revisit setup and test it after it will be refactored to worker-service
- ingress configuration for - api-definition request  handling

Helm chart updates

---

Cargo.lock
golem-shard-manager/Cargo.toml
golem-shard-manager/src/model.rs
golem-shard-manager/src/rebalancing.rs
golem-shard-manager/src/server.rs
golem-shard-manager/src/shard_management.rs
golem-worker-executor-base/src/grpc.rs
scripts/generate-golem-client.sh

https://www.notion.so/GOL-259-Attempt-to-fix-the-new-rebalancing-logic-eaeb9a8aeeb04466a5b36f8ab045ea8d

GOL-259 Attempt to fix the new rebalancing logic

---

Cargo.lock
golem-api-grpc/proto/golem/shardmanager/pod.proto
golem-api-grpc/proto/golem/shardmanager/shard_manager_service.proto
golem-shard-manager/Cargo.toml
golem-shard-manager/config/shard-manager.toml
golem-shard-manager/src/error.rs
golem-shard-manager/src/healthcheck.rs
golem-shard-manager/src/model.rs
golem-shard-manager/src/server.rs
golem-shard-manager/src/shard_management.rs
golem-shard-manager/src/shard_manager_config.rs
golem-shard-manager/src/worker_executor.rs
golem-worker-executor-base/Cargo.toml
golem-worker-executor-base/src/grpc.rs
golem-worker-executor-base/src/lib.rs
golem-worker-executor-base/src/services/shard_manager.rs
golem-worker-service/src/evaluator.rs
golem-worker-service/src/expr.rs

https://www.notion.so/GOL-219-Optional-kubernetes-based-health-check-for-sharding-manager-c1df33628c31427da9e99ad9fe58f1b6

GOL-219 Optional kubernetes based health check for sharding manager

---

.gitmodules

https://www.notion.so/Change-submodule-links-6ff53cbc4aea4f5298f2a9ee1cb8edd3

Change submodule links

---

.gitmodules
Cargo.lock
Cargo.toml
golem-api-grpc/Cargo.toml
golem-api-grpc/build.rs
golem-common/Cargo.toml
golem-service-base/Cargo.toml
golem-template-service/Cargo.toml
golem-worker-executor-base/Cargo.toml
golem-worker-executor/Cargo.toml
golem-worker-service-base/Cargo.toml
golem-worker-service/Cargo.toml

Using a published wasm-rpc crate

---

.github/workflows/ci.yaml
.gitmodules
Cargo.lock
Cargo.toml
scripts/generate-golem-client.sh
scripts/generate-openapi-yaml.sh

Use a published version of golem-openapi-client-generator

---

Cargo.lock
golem-client/Cargo.toml
golem-client/build.rs
golem-client/src/lib.rs

Fixes #292 for the `golem` repo

Proper way to generate code from build.rs

---

.github/workflows/ci.yaml

Fixes for latest CI changes

---

Makefile.toml
golem-client/Cargo.toml
golem-client/build.rs

Do not compile everything on arm64

---

golem-service-base/src/service/auth.rs
golem-worker-service-base/src/service/template/default.rs
golem-worker-service-base/src/service/worker/default.rs

- Small fix to `WithAuth` definition and usage

Separate template and worker namespace in WorkerServiceDefault

---

golem-worker-service-base/src/auth.rs
golem-worker-service-base/src/service/api_definition.rs
golem-worker-service-base/src/service/worker/default.rs
golem-worker-service/src/api/register_api_definition_api.rs
golem-worker-service/src/service/mod.rs

Separate Template Namespace in RegisterApiDefinitionDefault

---

golem-service-base/src/model.rs
golem-service-base/src/service/auth.rs
golem-service-base/src/service/mod.rs
golem-worker-service-base/src/api/common.rs
golem-worker-service-base/src/api/error.rs
golem-worker-service-base/src/auth.rs
golem-worker-service-base/src/service/api_definition.rs
golem-worker-service-base/src/service/mod.rs
golem-worker-service-base/src/service/template/default.rs
golem-worker-service-base/src/service/template/error.rs
golem-worker-service-base/src/service/worker/default.rs
golem-worker-service-base/src/service/worker/error.rs
golem-worker-service/src/api/mod.rs
golem-worker-service/src/api/register_api_definition_api.rs
golem-worker-service/src/api/worker.rs
golem-worker-service/src/api/worker_connect.rs
golem-worker-service/src/grpcapi/worker.rs
golem-worker-service/src/lib.rs
golem-worker-service/src/service/mod.rs
golem-worker-service/src/service/template.rs
golem-worker-service/src/service/worker.rs
golem-worker-service/src/worker_request_to_http_response.rs

Accidental push to main. Need to make sure branch protections are correct

Revert remove namespace

---

Cargo.lock
Makefile.toml
golem-cli/Cargo.toml
golem-cli/src/clients.rs
golem-cli/src/clients/errors.rs
golem-cli/src/clients/health_check.rs
golem-cli/src/lib.rs
golem-cli/src/main.rs
golem-cli/src/version.rs
golem-shard-manager/Cargo.toml
golem-template-service/Cargo.toml

Checks the server versions against the cli version and show a warning when the server is newer.
Resolves #197

Check cli vs server versions

---

Cargo.lock
Cargo.toml
Makefile.toml
golem-api-grpc/proto/golem/worker/worker_service.proto
golem-api-grpc/proto/golem/workerexecutor/worker_executor.proto
golem-cli/Cargo.toml
golem-client/Cargo.toml
golem-common/src/model/mod.rs
golem-service-base/Cargo.toml
golem-service-base/src/model.rs
golem-shard-manager/src/model.rs
golem-shard-manager/src/worker_executor.rs
golem-worker-executor-base/src/grpc.rs
golem-worker-executor-base/src/services/worker_enumeration.rs
golem-worker-executor-base/tests/api.rs
golem-worker-executor-base/tests/common/mod.rs
golem-worker-service-base/src/service/worker/default.rs
golem-worker-service/src/api/worker.rs
golem-worker-service/src/grpcapi/worker.rs
openapi/golem-service.yaml

fixes: #298 
added REST and GRPC APIs

Workers enumeration APIs

---

Cargo.lock
golem-api-grpc/proto/golem/common/string_filter_comparator.proto
golem-api-grpc/proto/golem/worker/worker_filter.proto
golem-common/src/model/mod.rs
golem-worker-executor-base/Cargo.toml
golem-worker-executor-base/build.rs
golem-worker-executor-base/src/durable_host/golem/mod.rs
golem-worker-executor-base/src/durable_host/mod.rs
golem-worker-executor-base/src/services/recovery.rs
golem-worker-executor-base/src/worker.rs
golem-worker-executor-base/src/workerctx.rs
golem-worker-executor-base/tests/api.rs
golem-worker-executor-base/tests/common/mod.rs
golem-worker-executor/src/context.rs
golem-worker-service-base/src/service/worker/default.rs
openapi/golem-service.yaml

fixes: #297 
related golem-wit PR: https://github.com/golemcloud/golem-wit/pull/17

Expose worker enumeration via host functions

---

Cargo.lock
golem-cli/Cargo.toml
golem-cli/src/api_definition.rs
golem-cli/src/clients.rs
golem-cli/src/clients/api_definition.rs
golem-cli/src/clients/errors.rs
golem-cli/src/clients/oas_api_definition.rs
golem-cli/src/clients/template.rs
golem-cli/src/lib.rs
golem-cli/src/main.rs
golem-cli/src/model.rs

Expose api-definition endpoints to golem-cli

---

.github/workflows/ci.yaml

Remainings of a reverted experiment

Remove unused publish steps from CI

---

Cargo.lock
Cargo.toml
golem-worker-executor-base/Cargo.toml
golem-worker-executor-base/src/durable_host/wasm_rpc/mod.rs
golem-worker-executor-base/src/services/rpc.rs
integration-tests/Cargo.toml

Resolves https://github.com/golemcloud/golem/issues/277
Must merge and publish and update dependency first:
- https://github.com/golemcloud/golem-wit/pull/18
- https://github.com/golemcloud/wasm-rpc/pull/28

Invoke function on the wasm-rpc interface

---

golem-common/src/model/mod.rs
golem-common/src/model/oplog.rs
golem-common/src/model/regions.rs
golem-common/src/redis.rs
golem-common/src/serialization.rs
golem-worker-executor-base/src/durable_host/durability.rs
golem-worker-executor-base/src/durable_host/http/serialized.rs
golem-worker-executor-base/src/durable_host/http/types.rs
golem-worker-executor-base/src/durable_host/mod.rs
golem-worker-executor-base/src/durable_host/serialized.rs

Drop the v1 oplog serialization format

---

golem-test-framework/src/components/worker_service/mod.rs
golem-test-framework/src/dsl/mod.rs
integration-tests/tests/worker.rs

get workers - integration tests

---

Cargo.lock
Cargo.toml
golem-cli/Cargo.toml
golem-cli/src/clients/template.rs
golem-cli/src/clients/worker.rs
golem-cli/src/main.rs
golem-cli/src/model.rs
golem-cli/src/model/invoke_result_view.rs
golem-cli/src/model/template.rs
golem-cli/src/model/wave.rs
golem-cli/src/template.rs
golem-cli/src/worker.rs
golem-cli/tests/cli.rs
golem-cli/tests/template.rs
golem-cli/tests/worker.rs

Fix: #245 
`--human-readable` flag in `invoke-and-await` is temporary. I'll replace it with a new global format later.

245 wasm wave representation

---

CONTRIBUTING.md
Makefile.toml

fix incorrect documentation in relation to IT tests

contributing - IT tests

---

Cargo.lock
golem-cli/Cargo.toml
golem-cli/src/api_definition.rs
golem-cli/src/main.rs
golem-cli/src/model.rs
golem-cli/src/model/text.rs
golem-cli/src/template.rs
golem-cli/src/worker.rs
golem-cli/tests/cli.rs
golem-cli/tests/main.rs
golem-cli/tests/text.rs
golem-cli/tests/worker.rs

Fix: #401 
No tests for api definitions yet - I'll add them in #411 .

401 human readable results

---

Makefile.toml
golem-cli/src/api_definition.rs
golem-cli/src/clients/api_definition.rs
golem-cli/src/model/text.rs
golem-cli/tests/api_definition.rs
golem-cli/tests/main.rs
golem-cli/tests/text.rs
golem-cli/tests/worker.rs

411 api definition add/update/import and tests

---

golem-cli/src/api_definition.rs
golem-cli/src/clients/api_definition.rs
golem-cli/src/model/text.rs
golem-cli/tests/api_definition.rs
golem-cli/tests/text.rs
golem-worker-service/src/api/register_api_definition.rs
openapi/golem-service.yaml

427 api definition rest endpoints

---

Cargo.toml
golem-cli/Cargo.toml

Fixes https://github.com/golemcloud/wasm-rpc/issues/35

Update to wasm-rpc 0.0.22

---

Cargo.lock
golem-service-base/Cargo.toml
golem-service-base/src/lib.rs
golem-service-base/src/service/template_object_store.rs
golem-service-base/src/stream.rs
golem-template-service/src/api/template.rs
golem-template-service/src/grpcapi/template.rs
golem-template-service/src/service/template.rs

Download template as stream

---

golem-cli/src/api_definition.rs
golem-cli/src/api_deployment.rs
golem-cli/src/clients.rs
golem-cli/src/clients/api_definition.rs
golem-cli/src/clients/api_deployment.rs
golem-cli/src/clients/errors.rs
golem-cli/src/lib.rs
golem-cli/src/main.rs
golem-cli/src/model/text.rs
golem-cli/tests/api_deployment.rs
golem-cli/tests/main.rs
golem-cli/tests/text.rs
golem-worker-service/src/api/deploy_api_definition.rs
golem-worker-service/src/api/register_api_definition.rs
openapi/golem-service.yaml

Resolves #428 
Also updates OpenAPI for deployments.

428 api deployment in cli

---

golem-test-framework/src/components/component_service/k8s.rs
golem-test-framework/src/components/component_service/mod.rs
golem-test-framework/src/components/component_service/spawned.rs
golem-test-framework/src/components/k8s.rs
golem-test-framework/src/components/mod.rs
golem-test-framework/src/components/rdb/docker_postgres.rs
golem-test-framework/src/components/rdb/k8s_postgres.rs
golem-test-framework/src/components/rdb/mod.rs
golem-test-framework/src/components/redis/k8s.rs
golem-test-framework/src/components/redis/mod.rs
golem-test-framework/src/components/shard_manager/k8s.rs
golem-test-framework/src/components/shard_manager/mod.rs
golem-test-framework/src/components/shard_manager/spawned.rs
golem-test-framework/src/components/worker_executor/k8s.rs
golem-test-framework/src/components/worker_executor/mod.rs
golem-test-framework/src/components/worker_executor/spawned.rs
golem-test-framework/src/components/worker_executor_cluster/k8s.rs
golem-test-framework/src/components/worker_service/k8s.rs
golem-test-framework/src/components/worker_service/mod.rs
golem-test-framework/src/components/worker_service/spawned.rs
golem-test-framework/src/config/cli.rs

related to: #377
- configuration for timeouts
- aws - routing with service load balancer (aws nlb)

Bench aws fixes

---

golem-cli/src/clients/worker.rs
golem-cli/src/model.rs
golem-cli/src/worker.rs
golem-cli/tests/worker.rs

Worker update in CLI

---

golem-api-grpc/proto/golem/apidefinition/api_definition.proto
golem-api-grpc/proto/golem/apidefinition/api_definition_error.proto
golem-cli/src/api_definition.rs
golem-cli/tests/api_definition.rs
golem-cli/tests/api_deployment.rs
golem-worker-service-base/src/api/common.rs
golem-worker-service-base/src/api/register_api_definition_api.rs
golem-worker-service-base/src/api_definition/api_common.rs
golem-worker-service-base/src/api_definition/http/http_api_definition.rs
golem-worker-service-base/src/api_definition/http/http_oas_api_definition.rs
golem-worker-service-base/src/api_definition/mod.rs
golem-worker-service-base/src/repo/api_definition_repo.rs
golem-worker-service-base/src/service/api_deployment.rs
golem-worker-service/src/api/register_api_definition.rs
openapi/golem-service.yaml

429 immutable api definition

---

Cargo.lock
golem-test-framework/Cargo.toml
golem-test-framework/src/config/cli.rs
golem-test-framework/src/dsl/benchmark.rs
integration-tests/src/benchmarks/cold_start_large.rs
integration-tests/src/benchmarks/cold_start_medium.rs
integration-tests/src/benchmarks/cold_start_small.rs
integration-tests/src/benchmarks/durability_overhead.rs
integration-tests/src/benchmarks/latency_large.rs
integration-tests/src/benchmarks/latency_medium.rs
integration-tests/src/benchmarks/latency_small.rs
integration-tests/src/benchmarks/mod.rs
integration-tests/src/benchmarks/simple_worker_echo.rs
integration-tests/src/benchmarks/suspend_worker.rs

378 benchmark matrix

---

Cargo.lock
Makefile.toml
golem-cli/src/clients/errors.rs
golem-cli/src/model.rs
golem-cli/tests/worker.rs
golem-client/Cargo.toml
golem-common/src/redis.rs
golem-worker-executor-base/src/durable_host/filesystem/types.rs
golem-worker-executor-base/src/durable_host/mod.rs

Might be a cherry pick in #477

update client generator

---

Cargo.lock
golem-common/src/model/oplog.rs
golem-component-compilation-service/config/component-compilation-service.toml
golem-worker-executor-base/Cargo.toml
golem-worker-executor-base/config/worker-service.toml
golem-worker-executor-base/src/durable_host/durability.rs
golem-worker-executor-base/src/durable_host/http/types.rs
golem-worker-executor-base/src/durable_host/mod.rs
golem-worker-executor-base/src/lib.rs
golem-worker-executor-base/src/services/golem_config.rs
golem-worker-executor-base/src/services/invocation_queue.rs
golem-worker-executor-base/src/services/oplog.rs
golem-worker-executor-base/src/services/worker.rs
golem-worker-executor-base/src/storage/blob/fs.rs
golem-worker-executor-base/src/storage/blob/memory.rs
golem-worker-executor-base/src/storage/blob/mod.rs
golem-worker-executor-base/src/storage/blob/s3.rs
golem-worker-executor-base/src/worker.rs
golem-worker-executor/config/worker-executor.toml
test-components/zig-3/wit/zig-3.wit

External oplog payloads

---

golem-test-framework/src/components/worker_executor_cluster/docker.rs
golem-test-framework/src/components/worker_executor_cluster/k8s.rs
golem-test-framework/src/components/worker_executor_cluster/spawned.rs
golem-test-framework/src/config/cli.rs
golem-test-framework/src/config/env.rs
golem-test-framework/src/config/mod.rs

482 parallel test env startup

---

kube/README.md
kube/deploy.sh
kube/golem-chart/templates/deployment.yaml
kube/golem-chart/templates/pvc.yaml
kube/golem-chart/values.yaml

helm chart fixes in relation to v0.0.103 changes 
* tested with pvc storage setup 
* tested in aws with s3 storage setup

Helm chart fixes

---

golem-cli/src/main.rs
golem-cli/src/oss/command.rs
golem-cli/src/oss/main.rs

565 reduce cloud code duplication

---

golem-cli/src/cloud.rs

565 pub fields

---

golem-cli/src/command/profile.rs
golem-cli/src/command/worker.rs
golem-cli/src/config.rs
golem-cli/src/init.rs
golem-cli/src/main.rs
golem-cli/src/oss/main.rs
golem-cli/tests/worker.rs

565 fix profile switch

---

Cargo.lock
golem-worker-executor-base/Cargo.toml
golem-worker-executor-base/config/worker-service.toml
golem-worker-executor-base/src/lib.rs
golem-worker-executor-base/src/services/golem_config.rs
golem-worker-executor/config/worker-executor.toml

Configure and query memory related information

---

Cargo.lock
Cargo.toml
golem-api-grpc/proto/golem/component/component_metadata.proto
golem-api-grpc/proto/golem/component/linear_memory.proto
golem-api-grpc/proto/golem/worker/worker_metadata.proto
golem-cli/src/model.rs
golem-cli/src/model/invoke_result_view.rs
golem-common/src/model/mod.rs
golem-common/src/model/oplog.rs
golem-component-service-base/src/service/component_processor.rs
golem-component-service/src/service/component.rs
golem-service-base/src/model.rs
golem-test-framework/src/dsl/mod.rs
golem-worker-executor-base/src/durable_host/mod.rs
golem-worker-executor-base/src/grpc.rs
golem-worker-executor-base/src/services/component.rs
golem-worker-executor-base/src/services/oplog/tests.rs
golem-worker-executor-base/src/services/worker.rs
golem-worker-executor-base/src/worker.rs
golem-worker-executor-base/src/workerctx.rs
golem-worker-executor-base/tests/api.rs
golem-worker-executor-base/tests/common/mod.rs
golem-worker-executor/src/context.rs
golem-worker-service-base/src/evaluator/evaluator_context.rs
golem-worker-service-base/src/http/http_request.rs
golem-worker-service-base/src/service/component/default.rs
golem-worker-service-base/src/service/worker/default.rs
openapi/golem-service.yaml

Storing linear memory size and component size in metadata

---

golem-cli/src/command/profile.rs
golem-cli/src/init.rs
golem-cli/src/oss/command.rs

Allow `-F` anywhere in cli command

make cli format global

---

Cargo.lock
docker-compose-postgres.yaml
docker-examples/docker-compose-postgres.yaml
docker-examples/docker-compose-sqlite.yaml
golem-shard-manager/Cargo.toml
golem-shard-manager/src/server.rs

docker-compose fixes, shard-manager cryptoprovider

---

golem-worker-service-base/src/api/common.rs
golem-worker-service-base/src/repo/api_deployment.rs
golem-worker-service-base/src/service/api_definition.rs
golem-worker-service-base/src/service/api_deployment.rs
golem-worker-service-base/tests/services_tests.rs
golem-worker-service/src/api/api_definition.rs
golem-worker-service/src/service/mod.rs

fixes: #638 
check for deployments conflicts, tests improvements
TODO:

api_deployment - check for conflicts, tests

---

golem-worker-executor-base/src/durable_host/golem/mod.rs
golem-worker-executor-base/src/durable_host/mod.rs

Resolves #321 
Most of the work was done in previous PRs, this is just a final small cleanup

Final cleanups to durableworkerctx

---

golem-test-framework/src/components/component_compilation_service/docker.rs
golem-test-framework/src/components/component_compilation_service/k8s.rs
golem-test-framework/src/components/component_compilation_service/mod.rs
golem-test-framework/src/components/component_compilation_service/spawned.rs
golem-test-framework/src/components/component_service/docker.rs
golem-test-framework/src/components/component_service/k8s.rs
golem-test-framework/src/components/component_service/mod.rs
golem-test-framework/src/components/component_service/spawned.rs
golem-test-framework/src/components/mod.rs
golem-test-framework/src/components/shard_manager/docker.rs
golem-test-framework/src/components/shard_manager/k8s.rs
golem-test-framework/src/components/shard_manager/mod.rs
golem-test-framework/src/components/shard_manager/spawned.rs
golem-test-framework/src/components/worker_executor/docker.rs
golem-test-framework/src/components/worker_executor/k8s.rs
golem-test-framework/src/components/worker_executor/mod.rs
golem-test-framework/src/components/worker_executor/spawned.rs
golem-test-framework/src/components/worker_service/docker.rs
golem-test-framework/src/components/worker_service/k8s.rs
golem-test-framework/src/components/worker_service/mod.rs
golem-test-framework/src/components/worker_service/spawned.rs

Allow reusing test-framework in cloud.

Unify test framework

---

golem-component-compilation-service/src/grpc.rs
golem-component-service-base/src/api/common.rs
golem-component-service-base/src/api/mod.rs
golem-component-service/src/grpcapi/component.rs
golem-shard-manager/src/error.rs
golem-shard-manager/src/lib.rs
golem-shard-manager/src/model.rs
golem-worker-service-base/src/api/common.rs
golem-worker-service/src/grpcapi/api_definition.rs
golem-worker-service/src/grpcapi/worker.rs

tracing for grpc api calls

---

golem-common/src/metrics.rs
golem-component-compilation-service/src/grpc.rs
golem-component-service-base/src/api/common.rs
golem-component-service-base/src/service/component.rs
golem-component-service/src/api/component.rs
golem-component-service/src/grpcapi/component.rs
golem-service-base/src/model.rs
golem-shard-manager/src/error.rs
golem-shard-manager/src/lib.rs
golem-worker-executor-base/src/error.rs
golem-worker-executor-base/src/grpc.rs
golem-worker-executor-base/src/metrics.rs
golem-worker-executor-base/src/services/worker_enumeration.rs
golem-worker-service-base/src/api/common.rs
golem-worker-service-base/src/api/error.rs
golem-worker-service-base/src/service/api_definition.rs
golem-worker-service-base/src/service/api_deployment.rs
golem-worker-service-base/src/service/worker/connect_stream.rs
golem-worker-service-base/src/service/worker/default.rs
golem-worker-service/src/api/api_definition.rs
golem-worker-service/src/api/api_deployment.rs
golem-worker-service/src/api/worker.rs
golem-worker-service/src/api/worker_connect.rs
golem-worker-service/src/grpcapi/api_definition.rs
golem-worker-service/src/grpcapi/worker.rs

related to: #662 and #663
- grpc api specific tracing was transformed to common api tracing with grpc and http types
- added tracing for rest/http apis
- changed logging in component and worker service to relay on existing spans
log snippet
```
2024-07-23T18:50:26.645000+0200  INFO api_request{api="get_latest_component_metadata" api_type="grpc" component_id="5ae09857-1ac1-445c-bdfd-baaa94abf792"}: golem_common::metrics::api: API request succeeded elapsed_ms=0
2024-07-23T18:50:26.646000+0200  INFO request{remote_addr=127.0.0.1 version=HTTP/1.0 method=POST uri=/v2/components/5ae09857-1ac1-445c-bdfd-baaa94abf792/workers/worker1/invoke-and-await?function=golem%3Ait%2Fapi.%7Bget-cart-contents%7D&calling-convention=Component}:api_request{api="invoke_and_await_function" api_type="http" …
```

Logs and tracing

---

golem-rib/src/expr.rs
golem-rib/src/parser/record.rs
golem-rib/src/text/mod.rs
golem-rib/src/text/writer.rs
golem-worker-executor-base/src/invocation.rs
golem-worker-executor-base/src/services/oplog/blob.rs
golem-worker-service-base/src/api_definition/http/http_api_definition.rs
golem-worker-service-base/src/http/http_request.rs
golem-worker-service-base/tests/services_tests.rs

expr eval - return error if parsing failed

---

golem-cli/Cargo.toml
golem-cli/src/oss/main.rs

Do not display warning about version check in default log level

---

Cargo.toml
golem-cli/Cargo.toml

golem-wasm-rpc 0.0.36

---

golem-cli/src/oss/clients/worker.rs
golem-component-service/src/api/component.rs
golem-component-service/src/api/mod.rs
golem-router/golem-services.conf.template
golem-router/golem-services.local.conf
golem-worker-service/src/api/mod.rs
golem-worker-service/src/api/worker.rs
kube/golem-chart/templates/ingress.yaml
openapi/golem-service.yaml

related to: #499 
change rest api version to v1

rest api v1

---

Makefile.toml
golem-service-base/Cargo.toml

fix in relation to: https://github.com/golemcloud/golem/actions/runs/10270539589/job/28419444099

golem-service-base - publish

---

golem-cli/src/init.rs
golem-cli/src/oss/main.rs

- Additional option for `init` command - default docker compose port
- Prevent version check warning during profile manipulations
- Fake commands in `--help` with no profile
Related #647

647 docker compose profile init

---

golem-common/src/uri/mod.rs

expose uri methods to reduce cloud code duplication

expose uri methods

---

docker-compose-postgres.yaml
docker-compose-sqlite.yaml
docker-examples/docker-compose-postgres.yaml
docker-examples/docker-compose-sqlite.yaml

`component_compiled_store` volume renamed to `worker_executor_store`

docker compose - worker_executor_store

---

.github/workflows/ci.yaml

Add .exe extension to published golem-cli binary for Windows

---

Cargo.lock
Cargo.toml

update of dependencies: poem, opentelemetry, prometheus 
solved a problem

http poem metrics fix

---

golem-rib/src/interpreter/result.rs
golem-rib/src/type_inference/variant_resolution.rs
golem-worker-service-base/src/worker_service_rib_interpreter/mod.rs

The updated test in this PR takes emulates a component that has a function called `process` which takes a variant that can be `follow`, `noop`, or `register`. The result of worker is the same variant. 
```scala
let user: str = request.body.user-id;
let action1 = register(user);
let action2 = follow("michael");
let action3 = noop;
let result = process(action1, action2, action3, user);
let x = match result {
follow(user)   => "follow ${user}",
register(user) => "register ${user}",
noop           => "noop"
};
let y = match action2 {
follow(user)   => "follow ${user}",
register(user) => "register ${user}",
noop           => "noop"
};
let z = match noop {
follow(user)   => "follow ${user}",
register(user) => "register ${user}",
noop           => "noop"
};
{ x: x, y: y, z: z }
```

Update variant test with both construction and pattern match

---

golem-cli/src/model/component.rs
golem-cli/src/service/worker.rs

Resolves: https://github.com/golemcloud/golem/issues/882

No curly brackets for functions without prefixes

---

golem-worker-executor-base/src/services/oplog/primary.rs
golem-worker-executor-base/src/storage/indexed/memory.rs
golem-worker-executor-base/src/storage/indexed/mod.rs
golem-worker-executor-base/src/storage/indexed/redis.rs
golem-worker-executor-base/tests/indexed_storage.rs
golem-worker-executor-base/tests/lib.rs

Indexed storage test suite and fixes

---

golem-worker-service-base/src/repo/api_definition.rs
golem-worker-service-base/src/service/api_deployment.rs
golem-worker-service-base/tests/services_tests.rs

set api definitions as draft when they are removed from deployment

---

golem-common/src/retriable_error.rs
golem-common/src/retries.rs
golem-service-base/src/routing_table.rs
golem-shard-manager/src/error.rs
golem-worker-executor-base/src/durable_host/mod.rs
golem-worker-executor-base/src/services/oplog/blob.rs
golem-worker-executor-base/src/services/oplog/compressed.rs
golem-worker-executor-base/src/services/oplog/mock.rs
golem-worker-executor-base/src/services/oplog/mod.rs
golem-worker-executor-base/src/services/oplog/multilayer.rs
golem-worker-executor-base/src/services/oplog/primary.rs
golem-worker-executor-base/src/services/oplog/tests.rs
golem-worker-executor-base/src/services/rpc.rs
golem-worker-executor-base/src/storage/blob/s3.rs
golem-worker-executor-base/tests/blob_storage.rs
golem-worker-service-base/src/service/worker/routing_logic.rs

Fixes [#1501](https://github.com/golemcloud/golem-cloud/issues/1501)

Fixes for oplog and blobstore related issues

---

Cargo.lock
golem-api-grpc/proto/golem/component/component.proto
golem-api-grpc/proto/golem/component/component_type.proto
golem-api-grpc/proto/golem/component/v1/component_service.proto
golem-cli/src/clients/component.rs
golem-cli/src/command/component.rs
golem-cli/src/model/component.rs
golem-cli/src/model/invoke_result_view.rs
golem-cli/src/oss/clients/component.rs
golem-cli/src/service/component.rs
golem-client/Cargo.toml
golem-common/src/model/mod.rs
golem-component-service-base/src/model.rs
golem-component-service-base/src/repo/component.rs
golem-component-service-base/src/service/component.rs
golem-component-service-base/tests/services_tests.rs
golem-component-service/db/migration/postgres/002__add_component_type.sql
golem-component-service/db/migration/sqlite/002__add_component_type.sql
golem-component-service/src/api/component.rs
golem-component-service/src/grpcapi/component.rs
golem-component-service/src/service.rs
golem-service-base/src/model.rs
golem-test-framework/src/components/component_service/mod.rs
golem-worker-service-base/src/service/component/default.rs
golem-worker-service-base/tests/services_tests.rs
openapi/golem-service.yaml

Introducing ephemeral component type

---

.github/workflows/benchmark.yaml
.github/workflows/ci.yaml

Fetch tags, so git describe is usable for versioning

Fetch tags

---

golem-common/src/golem_version.rs

Do no include dirty in version, as our builds modify the repo during publish

Do no include dirty in version

---

golem-rib/src/parser/binary_comparison.rs
golem-rib/src/parser/rib_expr.rs

Fixes #941 
The PR is more of a subtle refinement in the grammar to avoid all possible left recursions.
Now any expressions can be the operands in a binary. More tests are added, and they don't stack overflow.
The tests are running even faster.  On an average 0.5+ seconds ~> 0.1+ seconds for 430+ tests
The grammar change is as follows:
```scala
rib_expr ::=
pattern_match
| let_binding
| conditional
| binary_expr
| select_expr
| flag_or_record
| multi_line_block
| tuple
| sequence
| boolean_literal
| literal
| not_expr
| option_expr
| result_expr
| call_expr
| identifier
| number
.....
// left recursion
binary_expr ::= rib_expr operator rib_expr
```
```scala
rib_expr ::= simple_expr rib_expr_rest
simple_expr ::=
pattern_match
| let_binding
| conditional
| select_expr
| flag_or_record
| …
```

Investigate all possible left recursions and fix them

---

golem-common/src/model/mod.rs
golem-test-framework/src/dsl/mod.rs
golem-worker-executor-base/src/durable_host/mod.rs
golem-worker-executor-base/src/grpc.rs
golem-worker-executor-base/tests/api.rs
golem-worker-executor-base/tests/common/mod.rs
golem-worker-executor-base/tests/hot_update.rs
golem-worker-executor-base/tests/wasi.rs
integration-tests/tests/worker.rs

Fixes related to capturing stderr with failures

---

golem-rib/src/type_checker/mod.rs
golem-rib/src/type_checker/path.rs
golem-rib/src/type_checker/type_check_error.rs
golem-rib/src/type_checker/type_mismatch_call_args.rs
golem-rib/src/type_checker/unresolved_types.rs

Minor changes and clean ups:
* Better contextual messages, feedback messages
* Stop consuming errors too much for nested structures
* Cleanup path, index etc

Incremental cleanup

---

Cargo.lock
Cargo.toml
golem-rib/src/type_checker/type_mismatch_call_args.rs
golem-test-framework/src/components/worker_service/forwarding.rs
golem-test-framework/src/config/env.rs
golem-worker-executor-base/src/services/blob_store.rs
golem-worker-executor-base/src/services/oplog/blob.rs
golem-worker-executor-base/src/services/oplog/multilayer.rs
golem-worker-executor-base/src/services/oplog/tests.rs
golem-worker-executor-base/src/services/worker.rs
golem-worker-executor-base/src/services/worker_event.rs
golem-worker-executor-base/src/storage/blob/fs.rs
golem-worker-executor-base/src/storage/blob/memory.rs
golem-worker-executor-base/src/storage/blob/mod.rs
golem-worker-executor-base/src/storage/blob/s3.rs
golem-worker-executor-base/src/storage/blob/sqlite.rs
golem-worker-executor-base/tests/api.rs
golem-worker-executor-base/tests/blob_storage.rs
golem-worker-executor-base/tests/hot_update.rs
golem-worker-executor-base/tests/wasi.rs
integration-tests/tests/worker.rs

Fixes and more tests

---

golem-worker-executor-base/src/services/file_loader.rs

I saw the [test failure on master](https://github.com/golemcloud/golem/actions/runs/11753754003/job/32746966597) and looked into the cause.
The problem is that the file-loader uses the key of the intial file as the path of the file in it's local cache. This can run into the following sequence when multiple workers are using the same file:
1. Worker A requires file a
2. file loader downloads the file and stores a copy in ${cache_dir}/a. It returns an Arc to the worker that will delete the file when it's dropped
3. Worker A is shutting down and drops the last Arc for file a. This removes it from the cache as weak.upgrade is now going to fail. The file is not yet deleted.
3. Worker B requires file a
4. file loader checks the cache and doesn't find it. It creates a new cache entry and starts …

Initial file system followup: Fix race condition in file-loader

---

golem-worker-executor-base/src/services/worker_event.rs

Fix worker connect historical event ordering

---

golem-common/src/model/oplog.rs
golem-worker-executor-base/src/model/public_oplog/mod.rs
golem-worker-executor-base/tests/observability.rs

Fix the way get-oplog calculates the initial component version

---

Cargo.lock
Cargo.toml
golem-cli/Cargo.toml
golem-cli/src/command.rs
golem-cli/src/command/component.rs
golem-cli/src/oss/cli.rs

TODO: bump wasm-rpc after https://github.com/golemcloud/wasm-rpc/pull/105

Update wasm-rpc-stubgen usage, cli deprecations

---

golem-cli/src/command/component.rs
wasm-rpc-stubgen/src/commands/app.rs
wasm-rpc-stubgen/src/commands/generate.rs
wasm-rpc-stubgen/src/model/app.rs
wasm-rpc-stubgen/src/wit_resolve.rs

Resolves https://github.com/golemcloud/wasm-rpc/issues/106

Introduced new static-wasm-rpc dependency type and made wasm-rpc the stubless one

---

Cargo.lock
Cargo.toml
golem-cli/tests/api_definition.rs
golem-cli/tests/api_deployment.rs
golem-cli/tests/api_deployment_fileserver.rs
golem-cli/tests/component.rs
golem-cli/tests/profile.rs
golem-cli/tests/text.rs
golem-cli/tests/worker.rs
golem-service-base/tests/blob_storage.rs
golem-worker-executor-base/tests/indexed_storage.rs
golem-worker-executor-base/tests/key_value_storage.rs

Using test-r's new dependency matrix feature

Updated test-r

---

golem-rib/src/compiler/mod.rs
golem-rib/src/interpreter/rib_interpreter.rs

Add missing tests for #1289

---

Makefile.toml
wasm-rpc-stubgen/tests/add_dep.rs
wasm-rpc-stubgen/tests/wit.rs

Fix and reenable wasm-rpc-stubgen tests

---

.github/workflows/ci.yaml
Cargo.lock
Cargo.toml
Makefile.toml
golem-component-service/Cargo.toml
golem-component-service/src/lib.rs
golem-worker-service/Cargo.toml
golem-worker-service/src/lib.rs
wit/deps.lock
wit/deps/golem-1.x/golem-host.wit
wit/deps/golem-1.x/golem-oplog-processor.wit
wit/deps/golem-1.x/golem-oplog.wit
wit/deps/golem-durability/golem-durability-1.2.wit

- Expose DB migrations for the extracted golem executable
- Add local up-to-date checks for wit-deps
- Add CI Git up-to-date checks for wit-deps

Expose rds migrations, wit-deps checks

---

golem-worker-executor-base/src/durable_host/durability.rs
golem-worker-executor-base/src/durable_host/http/types.rs
golem-worker-executor-base/src/durable_host/wasm_rpc/mod.rs
golem-worker-executor-base/src/preview2/mod.rs
golem-worker-executor-base/tests/common/mod.rs
golem-worker-executor/src/context.rs
wasm-rpc/src/lib.rs

Export wasi bindings from wasm-rpc and remove all transmutes

---

golem-test-framework/src/components/rdb/docker_mysql.rs
golem-test-framework/src/components/rdb/docker_postgres.rs
golem-worker-executor-base/tests/rdbms_service.rs

rdbms parallel test with using multiple databases

---

golem-common/src/model/plugin.rs
golem-component-service-base/src/repo/component.rs
golem-component-service-base/src/repo/plugin.rs
golem-component-service-base/src/service/component.rs
golem-component-service-base/src/service/component_compilation.rs
golem-component-service-base/src/service/component_object_store.rs
golem-component-service-base/src/service/plugin.rs
golem-component-service-base/tests/all/service/mod.rs
golem-component-service/src/api/component.rs
golem-component-service/src/api/mod.rs
golem-component-service/src/grpcapi/component.rs
golem-component-service/src/grpcapi/mod.rs
golem-component-service/src/service.rs
golem-service-base/src/service/initial_component_files.rs
golem-service-base/src/service/plugin_wasm_files.rs
golem-test-framework/src/components/component_compilation_service/docker.rs
golem-test-framework/src/components/component_service/docker.rs
golem-test-framework/src/components/shard_manager/docker.rs
golem-test-framework/src/components/worker_executor/docker.rs
golem-test-framework/src/components/worker_service/docker.rs
openapi/golem-service.yaml

Check oplog processor plugins implement the proper interface

---

golem-common/src/model/plugin.rs

Resolves https://github.com/golemcloud/golem/issues/1299

Fix DefaultPluginOwner serialization

---

golem-worker-service-base/src/service/gateway/api_definition.rs

Fix get_all_components

---

golem-worker-executor-base/src/durable_host/durability.rs
wasm-rpc/src/extractor.rs
wit/deps.lock
wit/deps.toml
wit/deps/golem-durability/golem-durability-1.2.wit

- Adds new host function to read `ValueAndType` payloads in libraries using custom durability
- Adds missing trait implementation for `WitValue` extractors

Golem durability typed read

---

golem-component-service-base/src/model/mod.rs
golem-component-service-base/src/repo/component.rs
golem-component-service-base/src/service/component.rs
golem-component-service-base/tests/all/repo/mod.rs
golem-component-service-base/tests/all/repo/postgres.rs
golem-component-service-base/tests/all/repo/sqlite.rs
golem-component-service-base/tests/all/service/mod.rs
golem-component-service/src/api/component.rs
golem-service-base/src/model.rs
openapi/golem-service.yaml

Fixes #1469 
The PR is implemented based on the features required by @noise64  and made the search a POST. This is what we and noise thought so.

Component search (multiple names with each one having specific details)

---

golem-client/build.rs
golem-common/src/model/plugin.rs
golem-component-service-base/src/model/component.rs
golem-component-service-base/src/repo/component.rs
golem-component-service-base/src/service/component.rs
golem-component-service-base/tests/all/repo/mod.rs
golem-component-service/src/api/component.rs
openapi/golem-service.yaml

Required for https://github.com/golemcloud/golem-cli/issues/105

Exposed plugin installation management as a batch operation

---

golem-api-grpc/proto/golem/component/component.proto
golem-api-grpc/proto/golem/component/v1/component_service.proto
golem-common/src/testing.rs
golem-component-service-base/src/api/dto.rs
golem-component-service-base/src/api/mapper.rs
golem-component-service-base/src/model/component.rs
golem-component-service-base/src/model/mod.rs
golem-component-service-base/src/repo/component.rs
golem-component-service-base/src/service/component.rs
golem-component-service-base/tests/all/repo/mod.rs
golem-component-service-base/tests/all/service/mod.rs
golem-component-service/db/migration/postgres/012__component_env.sql
golem-component-service/db/migration/sqlite/012__component_env.sql
golem-component-service/src/api/component.rs
golem-component-service/src/grpcapi/component.rs
golem-service-base/src/model.rs
golem-test-framework/src/components/component_service/filesystem.rs
golem-test-framework/src/components/component_service/mod.rs
golem-test-framework/src/dsl/mod.rs
golem-worker-executor-base/src/services/component.rs
golem-worker-executor-base/src/worker/mod.rs
golem-worker-executor-base/tests/api.rs
golem-worker-executor-base/tests/measure_test_component_mem.rs
golem-worker-service-base/tests/services_tests.rs
integration-tests/tests/api/api_deployment.rs
integration-tests/tests/api/component.rs
openapi/golem-service.yaml

Fixes #1549 
Cloud PR: https://github.com/golemcloud/golem-cloud/pull/1669

Component Env

---

integration-tests/tests/api/api_definition.rs

API Tests for all PR have been Failing due to PR #1569 , This fixes that. I tested locally. Fingers crossed CI passes. @vigoo The API Tests passes, and this should fix the failing test.

Fix for Integration-tests

---

golem-api-grpc/proto/golem/worker/worker_metadata.proto
golem-client/build.rs
golem-common/src/model/regions.rs
golem-test-framework/src/components/worker_service/mod.rs
golem-worker-executor/src/grpc/mod.rs
golem-worker-service/src/model.rs
openapi/golem-service.yaml
openapi/golem-worker-service.yaml

Exposed skipped and deleted regions in the public worker metadata

---

Cargo.toml
golem-worker-service/src/gateway_api_definition/http/api_oas_convert.rs
wasm-rpc/Cargo.toml

Build with panic=abort

---

golem-test-framework/src/components/rdb/docker_postgres.rs

Missed out this in my previous PR

Add network config in Postgres container

---

golem-common/src/model/agent/mod.rs
golem-debugging-service/src/debug_session.rs
golem-debugging-service/src/from_value.rs
golem-worker-executor/src/durable_host/dynamic_linking/wasm_rpc.rs
golem-worker-executor/src/durable_host/golem/v1x.rs
golem-worker-executor/src/durable_host/mod.rs
golem-worker-executor/src/durable_host/wasm_rpc/mod.rs
golem-worker-executor/src/durable_host/wasm_rpc/serialized.rs
golem-worker-executor/src/grpc/invocation.rs
golem-worker-executor/src/grpc/mod.rs
golem-worker-executor/src/model/public_oplog/mod.rs
golem-worker-executor/src/services/component.rs
golem-worker-executor/src/services/rpc.rs
golem-worker-executor/src/services/scheduler.rs
golem-worker-executor/src/worker/invocation_loop.rs
golem-worker-executor/src/worker/mod.rs

Resolves #1832 
Resolves #1833

More agent related information in server spans, invocation contexts and public oplog entries

---

Makefile.toml

The low-level-agent kept reappearing when using build

Makefile.toml: wit-test-components cleanup

---

golem-common/src/model/agent/mod.rs
golem-worker-executor/src/worker/mod.rs
wasm-rpc-derive/src/lib.rs

Fix agent initialization

---

cli/golem-cli/src/command_handler/interactive.rs

Switch the order of the app new interactive menu

---

cli/golem-cli/src/model/agent/moonbit.rs
cli/golem-cli/src/model/agent/test.rs
cli/golem-cli/src/model/agent/wit.rs

Fix enum support in moonbit wrapper

---

golem-common/src/model/agent/mod.rs
wasm-rpc/src/value_and_type.rs

Fixes two value-conversion related issues
Resolves https://github.com/golemcloud/golem/issues/2118

Fix value conversion issues
