golem-cloud-server-oss/src/grpcapi/template.rs
golem-common/proto/services/template_service.proto
golem-worker-executor-base/src/durable_host/mod.rs
golem-worker-executor-base/src/workerctx.rs
golem-worker-executor-base/tests/common/mod.rs
golem-worker-executor-base/tests/lib.rs
golem-worker-executor-oss/src/context.rs
golem-worker-executor-oss/src/lib.rs

The generic way that was supposed to "auto implement" parts of `WorkerCtx` for the leaf contexts was not working in practice due to various ownership and coherence rules. 
So with this change the final context type requires manual implementation of the full worker context, but for each method which is not to be customized, it can be a single forward call to the inner `DurableWorkerCtx`.

Remove HasDurableWorkerCtx as it was not usable in practice

---

.github/workflows/ci.yaml
Cargo.lock
Cargo.toml
golem-api-grpc/Cargo.toml
golem-cloud-server-base/Cargo.toml
golem-cloud-server-oss/Cargo.toml
golem-common/Cargo.toml
golem-shard-manager/Cargo.toml
golem-worker-executor-base/Cargo.toml
golem-worker-executor-oss/Cargo.toml

- Checked unused dependencies with `cargo-udeps`
- Manually checked all non-workspace dependencies and moved the duplicated ones to workspace level
- Manually updated all dependencies to lates where possible - some of them cannot be updated to keep compatible with the current `wasmtime` version
- Updated the lock file with `cargo update`

Clean-up dependencies

---

docker-compose.yml
golem-cloud-server-base/src/typechecker.rs
golem-worker-executor-base/src/wasm_types.rs

If we Invoke function with partial information in the function parameter which is of `Record` type, then golem-cli doesn't respond with any error and looks to be hanging forever.
This is a minor fix.
More details here: https://www.notion.so/golemcloud/Golem-OSS-CLI-Testing-893dbb95d2054044afdedc5a49906b9d

Return error when there is decode error for record

---

docker-examples/docker-compose-postgres.yaml

```cmd
docker-examples % docker-compose -f docker-compose-postgres.yaml up
```
failing with first start, as golem-service trying to init postgres db (migrations), which is not completely started yet
with restart on failure, golem-service will recover
```logs
golem-service-1          | 2024-02-03T18:54:51.020960Z  INFO golem_service::db: DB migration: postgresql://postgres:5432/golem_db
golem-service-1          | [golem-service/src/server.rs:51] "DB - init error: {}" = "DB - init error: {}"
golem-service-1          | [golem-service/src/server.rs:51] e = Io(
golem-service-1          |     Os {
golem-service-1          |         code: 111,
golem-service-1          |         kind: ConnectionRefused,
golem-service-1          |         message: "Connection refused",
golem-service-1          | …
```

docker examples postgres - golem-service restart on failure

---

CONTRIBUTING.md

Trying to build golem services locally 
```
cargo build --release --target aarch64-unknown-linux-gnu-gcc
```
fails because wasmtime is not found if the git submodules are not initiated and updated.
This PR adds this detail in the documentation

docs: include git submodule info

---

Cargo.lock
api-gateway-examples/README.md
golem-worker-bridge/Cargo.toml
golem-worker-bridge/src/api/api_definition_endpoints.rs
golem-worker-bridge/src/api/custom_request_endpoint.rs
golem-worker-bridge/src/api_definition.rs
golem-worker-bridge/src/main.rs
golem-worker-bridge/src/oas_worker_bridge.rs
golem-worker-bridge/src/register.rs

While we think about versioning of worker bridge definitions (api-definition version), we should disallow mutating a definition for the same version.
cc @adamgfraser , something that we discussed.

Disallow updating the same version of endpoint definitions

---

golem-service/src/api/worker_connect.rs
golem-service/src/service/worker.rs

- Close connection with worker on client websocket close
- Forward stream to via mpsc channel which is Send + Sync, allowing for validation prior to upgradin the protocol to websocketg (because it can then be moved into future), and returning an http error.

Worker Connect Fixes

---

.github/workflows/ci.yaml
Cargo.lock
golem-worker-service/Cargo.toml

successful test of docker build: https://github.com/golemcloud/golem-services/actions/runs/8031310857/job/21939511221 (without docker push)
removed `reqwest = "0.11.24"` from golem-worker-service , which is not needed, and it is appending also`openssl` dependency, which then making issues with cross compilation

golem-worker-service - removed reqwest dep

---

golem-router/golem-services.conf.template

To avoid errors during upload templates of larger size (debug mode especially).
A shopping-cart debug mode creates 2+ megabytes. To be safer side I increased to 4m

Increase client_max_body_size for golem-router

---

api-gateway-examples/README.md
golem-api-grpc/proto/golem/shardmanager/shard_manager_service.proto
golem-shard-manager/config/shard-manager.toml
golem-shard-manager/src/model.rs
golem-shard-manager/src/persistence.rs
golem-shard-manager/src/rebalancing.rs
golem-shard-manager/src/server.rs
golem-shard-manager/src/shard_management.rs
golem-shard-manager/src/shard_manager_config.rs
golem-shard-manager/src/worker_executor.rs
golem-worker-executor-base/src/services/shard_manager.rs

- Rebalancing extracted to separate module
- Tests for rebalancing
- Improved rebalancing logic based on the tests, support up/downscaling and registering more than one pod at once
- Routing table is managed in an "actor like" way, with registering and healthcheck only indicating changes in the available pods in a non-blocking way. A single thread applies the changes to the routing table and sends out the updates to the workers and manages the persistency.
- The register gRPC call no longer returns immediately the associated shards, so it can use the above mentioned non-blocking registration. The registered workers gets assign messages the next time the routing table gets updated (which is immediate if there was no change in process already)
- Some small refactorings to reduce the number …

GOL-220 Shard manager improvements part 1

---

golem-shard-manager/src/shard_management.rs
golem-worker-service/src/service/worker.rs

Resolves #254 
Fixes two problems:
- In the shard manager, unhealthy pods were not properly removed from the table _when_ they did not have any assigned shards. This lead to unnecessary repeated health checks for them.
- The code that routes requests to different worker executors based on the routing table did not properly handle some error cases, and never updated the routing table if there was a connection issue (and not an invalid shard id). Now a connection error to a worker executor triggers a routing table invalidation (as well as a connection error to the shard manager - but that one is retried with a 1s delay while the pod access problem is retried immediately)

Sharding fixes

---

.gitmodules
Cargo.lock
Cargo.toml

Resolves #228 (but unlike the original idea, not publishing the wasmtime fork just using Cargo's git dependency)

Remove wasmtime as a submodule

---

golem-common/src/redis.rs
golem-worker-service-base/src/api_definition_repo.rs
golem-worker-service-base/src/auth.rs
golem-worker-service-base/src/service/api_definition_service.rs

Closes https://github.com/golemcloud/golem/issues/253
- Introduce convenience trait `ApiNamespace`
- Add transaction API 
- Each Namespace has it's own Redis Set containing all the `ApiDefinitionId`. This enables looking up all Api Definitions for a given namespace. Namespace now requires Encode/Decode trait bounds
- Each API Definition is also inserted uniquely by key 
- Add and Delete use Transaction api 
- Improve tests 
- TODO: Currently test is marked as `#ignore`, but we should really convert this to an integration test.  See https://github.com/golemcloud/golem/issues/264

Worker Service Base: Redis Impl

---

.gitignore
.gitmodules
Cargo.lock
golem-worker-executor-base/Cargo.toml
golem-worker-executor-base/build.rs
golem-worker-executor-base/src/preview2/mod.rs
test-templates/build-components.sh
test-templates/js-1/componentize.js
test-templates/js-2/componentize.js

Unfortunately `bindgen!` only accepts string literals so had to symlink the resolved crate to a fix relative path

Referencing golem-wit as a rust crate

---

golem-service-base/src/config.rs
golem-service-base/src/routing_table.rs
golem-template-service/src/config.rs
golem-worker-service-base/src/app_config.rs
golem-worker-service/src/config.rs

In some services for config types the `Default` instance was incorrectly used as the entry point for loading the external config (from toml files and environment variables).
This was very confusing and causes some surprises. 
The goal of the default instances is to provide a default value of the type which can be used as a baseline when programmatically creating a custom value of that type, so only the fields that differ from the default value need to be specified. It should not depend on any external resources like files and environment variables.
This PR cleans this up so now all services are implemented the same:
- `new()` constructor function on the top level config class to load it with the config library
- The `Default` instances are pure and just generate a reasonable default …

Clean up config default instances

---

golem-common/src/model/oplog.rs
golem-worker-executor-base/src/durable_host/golem/mod.rs
golem-worker-executor-base/src/durable_host/mod.rs
golem-worker-executor-base/src/grpc.rs
golem-worker-executor-base/src/worker.rs

Resolves #283 
Related to #321 
Notes:
- `create` is safe to be reexecuted because the (redis) promise implementation uses the `NX` flag 
- `await` has to be reexecuted because the worker goes suspended when the promise is not yet set, and only gets recovered once it has been completed. we need to reevaluate the promise state during that recovery
- `complete` need to be durable because we don't want to overwrite the completed promise's state 
- `delete` need to be durable to not try to delete a promise more than once

Cleanup and durability fixes for the promise API

---

docker-examples/docker-compose-postgres.yaml
docker-examples/docker-compose-sqlite.yaml

I bumped into this error when trying to bootstrap Golem infra locally
```
golem-worker-executor_1               | 2024-04-02T15:42:06.188727Z  INFO golem_worker_executor_base::services::template: Using template API at http://golem-template-service:9090/
golem-worker-executor_1               | 2024-04-02T15:42:06.188706Z  INFO Server::run{addr=0.0.0.0:8082}: warp::server: listening on http://0.0.0.0:8082/
golem-worker-executor_1               | thread 'main' panicked at /home/runner/work/golem/golem/golem-worker-executor-base/src/services/oplog.rs:59:35:
golem-worker-executor_1               | failed to get the number of replicas from Redis: IO Error: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }
golem-worker-executor_1               | stack backtrace: …
```

Make `golem-worker-executor` depend on `redis` in Docker Compose

---

golem-cli/src/worker.rs
golem-cli/tests/worker.rs

related to: #300 
```
golem-cli worker list -h
Retrieves metadata about an existing workers in a template
Usage: golem-cli worker list [OPTIONS] --template-id <TEMPLATE_ID> --template-name <TEMPLATE_NAME>
Options:
-T, --template-id <TEMPLATE_ID>
-v, --verbose...                     Increase logging verbosity
-q, --quiet...                       Decrease logging verbosity
-t, --template-name <TEMPLATE_NAME>
-f, --filter <FILTER>                Filter for worker metadata in form of `property op value`
-c, --cursor <CURSOR>                Position where to start listing, if not provided, starts from the beginning
-n, --count <COUNT>                  Count of listed values, if count is not provided, returns all values
-p, --precise <PRECISE>              Precision in relation to worker …
```

CLI - worker list, doc and count processing

---

golem-api-grpc/proto/golem/apidefinition/api_definition_service.proto
golem-cli/src/api_definition.rs
golem-cli/src/clients/errors.rs
golem-common/src/redis.rs
golem-worker-service-base/src/api/common.rs
golem-worker-service-base/src/repo/api_definition_repo.rs
golem-worker-service-base/src/service/api_definition.rs
golem-worker-service/src/api/mod.rs
golem-worker-service/src/api/register_api_definition.rs
golem-worker-service/src/grpcapi/register_api_definition.rs
openapi/golem-service.yaml

closes https://github.com/golemcloud/golem/issues/402
- Separate create/update methods for API Definitions
- `register` methods are renamed to `create`
- New NotFound Registry Error
- Made Internal errors `anyhow::Error` instead of `String`
- Export fred `RedisError` to implement `From<RedisError> for ApiRegistrationRepoError` instead of using `map_err` everywhere
- Remove `MessageBody` and `WorkerServiceErrorBody` in favor of `ErrorBody` which is used everywhere else in API

Api Definition: Separate Create and Update

---

golem-worker-executor-base/src/durable_host/durability.rs
golem-worker-executor-base/src/durable_host/io/streams.rs
golem-worker-executor-base/src/durable_host/mod.rs
golem-worker-executor-base/src/durable_host/sockets/ip_name_lookup.rs

Resolves #388 
- Checks the imported function's name during replay
- Payload deserialization errors are considered divergence
- Makes sure all divergence errors are reported as `GolemError::UnexpectedOplogEntry` so we can handle them during the update

Improved divergence detection

---

golem-test-framework/src/components/mod.rs
integration-tests/Cargo.toml
integration-tests/src/benchmarks/suspend_worker.rs

fixes: #384
```sh 
./target/debug/benchmark_suspend_worker --length 3 spawned
```
result
```
Results for 'worker-7':
Duration:
Avg: 10.036015666s
Min: 10.031044s
Max: 10.03895s
Results for 'worker-3':
Duration:
Avg: 10.035762222s
Min: 10.032683s
Max: 10.037873s
Results for 'worker-1':
Duration:
Avg: 10.036104666s
Min: 10.031829s
Max: 10.039348s
Results for 'worker-5':
Duration:
Avg: 10.035954666s
Min: 10.029747s
Max: 10.046311s
Results for 'worker-0':
Duration:
Avg: 10.035976888s
Min: 10.031721s
Max: 10.03879s
Results for 'worker-8':
Duration:
Avg: 10.035595222s
Min: 10.030308s
Max: 10.038076s
Results for 'worker-9':
Duration:
Avg: 10.036201333s
Min: 10.032083s
Max: 10.039173s
Results for 'worker-4':
Duration:
Avg: 10.035727666s
Min: 10.03134s
Max: 10.038s
Results for 'worker-2': …
```

Suspend bench

---

golem-cli/src/component.rs
golem-cli/src/model/text.rs
golem-cli/tests/component.rs
golem-cli/tests/text.rs

fixes: #487 
```
% golem-cli component -h
Upload and manage Golem components
Usage: golem-cli component [OPTIONS] <COMMAND>
Commands:
add     Creates a new component with a given name by uploading the component WASM
update  Updates an existing component by uploading a new version of its WASM
list    Lists the existing components
get     Get component
help    Print this message or the help of the given subcommand(s)
Options:
-v, --verbose...  Increase logging verbosity
-q, --quiet...    Decrease logging verbosity
-h, --help        Print help
% golem-cli component get --component-id 78b55b39-7f62-4c20-90e2-9e5f27c6f7a5
Component with ID 78b55b39-7f62-4c20-90e2-9e5f27c6f7a5. Version: 2. Component size is 117009 bytes.
Component name: cart.
Exports:
golem:it/api/initialize-cart(user-id: …
```

golem-cli component get

---

golem-test-framework/src/components/component_service/docker.rs
golem-test-framework/src/components/component_service/k8s.rs
golem-test-framework/src/components/component_service/mod.rs
golem-test-framework/src/components/component_service/spawned.rs
golem-test-framework/src/config/cli.rs
golem-test-framework/src/config/env.rs
integration-tests/src/benchmarks/cold_start_large.rs
integration-tests/src/benchmarks/cold_start_medium.rs
integration-tests/src/benchmarks/cold_start_small.rs
integration-tests/src/benchmarks/mod.rs

fixes: #381 
```
./target/debug/benchmark_cold_start_large --length 3  spawned --component-compilation-disabled
```
```
Results for 'invocation':
Duration:
Avg: 71.051333033s
Min: 70.671997s
Max: 71.675313s
Results for 'worker-0':
Duration:
Avg: 71.050806333s
Min: 70.674088s
Max: 71.674405s
Results for 'worker-1':
Duration:
Avg: 71.054380333s
Min: 70.674286s
Max: 71.673069s
Results for 'worker-2':
Duration:
Avg: 71.048819333s
Min: 70.674116s
Max: 71.673054s
Results for 'worker-3':
Duration:
Avg: 71.047746333s
Min: 70.673957s
Max: 71.672844s
Results for 'worker-4':
Duration:
Avg: 71.054834s
Min: 70.673949s
Max: 71.673285s
Results for 'worker-5':
Duration:
Avg: 71.056509666s
Min: 70.67404s
Max: 71.675313s
Results for 'worker-6':
Duration:
Avg: 71.0505s
Min: 70.673959s
Max: 71.674384s …
```

bench - component-compilation-disabled

---

.gitignore
CONTRIBUTING.md
Makefile.toml
golem-component-compilation-service/config/component-compilation-service.toml
golem-component-compilation-service/src/config.rs
golem-component-service/config/component-service.toml
golem-component-service/src/config.rs
golem-router/golem-services.local.conf
golem-shard-manager/config/shard-manager.toml
golem-shard-manager/src/shard_manager_config.rs
golem-worker-executor/config/worker-executor.toml
golem-worker-executor/src/services/config.rs
golem-worker-service/config/worker-service.toml
golem-worker-service/src/config.rs

Resolves #525 
Provides a simple alternative to run all services locally, in a way it is ready to be tested with `golem-cli`. 
`cargo make run` builds and starts all the services, having only 3 external dependencies:
- `redis`
- `nginx`
- `lnav`
On OSX all 3 can be installed by `brew`.
Note: 
I made the service's default configurations, which were previously partial and containing confusing random ports etc, the default configuration for running them locally. This makes it convenient to test things (you can just start all services, then kill one and manually run without having to deal with env vars etc). And in prod / docker the config is overridden anyway.

cargo make run task

---

golem-worker-executor-base/src/services/compiled_component.rs
golem-worker-executor-base/src/services/component.rs

Note: Wanted to do the same for loading the precompiled binaries, but that's not easy because it requires an `&Engine` which we cannot move to the closure.

Compiling on blocking thread pool

---

golem-component-service/config/component-service.toml

if there is 
```toml
[compilation.config]
host = "localhost"
port = 9091
```
in configuration, then `GOLEM__COMPILATION__TYPE=Disabled` failing
```
./target/debug/benchmark_cold_start_small  --json spawned --component-compilation-disabled
```
```
2024-06-06T20:47:46.606458Z  INFO golem_test_framework::components: Waiting for golem-component-service start on host localhost:9091, timeout: 90s
2024-06-06T20:47:48.391827Z ERROR golem_test_framework::components: [componentsvc] thread 'main' panicked at golem-component-service/src/config.rs:88:14:
2024-06-06T20:47:48.391870Z ERROR golem_test_framework::components: [componentsvc] Failed to parse config: Error { tag: Tag(Default, 2), profile: Some(Profile(Uncased { string: "default" })), metadata: Some(Metadata { name: "`GOLEM__` environment …
```

component-service - default configuration

---

.github/workflows/benchmark.yaml

I have to remove this to see a complete workflow of benchmark
* Throughput benchmark kept failing in my machine. Firstly we need to ensure its running as consistent as other benchmarks before having this as part of the CI workflow.
* I am currently looking at this. 
* This PR is to unblock rest of the benchmark jobs
* Also as I mentioned earlier, it was a good idea to keep the number of jobs minimal when we test a workflows, and that's why I didn't have all of these jobs and it wasn't accidental

Temporarily remove throughput benchmark

---

.github/workflows/benchmark.yaml

There was a difference between the script that tested vs what's deployed with golem.
Difference was looping through the files was listing directory in benchmark directory, vs hardcoded in the test-script.
It's hard to test shell script. In future, I will find some ways to move this back to Rust.

Fix script in benchmark file

---

CONTRIBUTING.md
golem-worker-service-base/src/api_definition/http/http_oas_api_definition.rs
golem-worker-service-base/src/evaluator/getter.rs
golem-worker-service-base/src/evaluator/math_op_evaluator.rs
golem-worker-service-base/src/evaluator/mod.rs
golem-worker-service-base/src/evaluator/pattern_match_evaluator.rs
golem-worker-service-base/src/http/http_request.rs
golem-worker-service-base/src/worker_binding/golem_worker_binding.rs
golem-worker-service-base/src/worker_binding/request_details.rs
golem-worker-service-base/src/worker_binding/worker_binding_resolver.rs
golem-worker-service-base/src/worker_bridge_execution/content_type_mapper.rs
golem-worker-service-base/src/worker_bridge_execution/to_response.rs

The main testing I wanted to do was upgrading wasm-rpc. I think the main contribution to wasm-rpc was wasm-rpc-stubgen (which is just my change allowing complex workflows)
Also also not sure whether we should release wasm-rpc before this [PR](https://github.com/golemcloud/wasm-rpc/pull/45) or simply give up on upgrading as such in this golem release
However, as part of the testing, I found the following behavior that got regressed in the API gateway.
This questioned the non existence of some unit tests. Therefore I added those tests.
The Rib expression always had optional headers etc when specifying response mapping. 
With Rib powerful in last couple of weeks, we also made it  mandatory (not quite intentional) to  specify status code, headers etc which can give horrible user experience …

Final touch before release - make headers, status back to optional fields (and upgrade wasm-rpc?)

---

golem-common/src/model/function_name.rs
golem-worker-service-base/src/api_definition/http/http_oas_api_definition.rs
golem-worker-service-base/src/evaluator/evaluator_context.rs
golem-worker-service-base/src/http/http_request.rs
golem-worker-service-base/src/parser/expr/expr_parser.rs
golem-worker-service-base/src/parser/expr/selection.rs
golem-worker-service-base/src/worker_binding/worker_binding_resolver.rs
golem-worker-service-base/src/worker_bridge_execution/to_response.rs

Please note, the sole purpose of this PR to get as minimal changes as possible into the API Gateway's Rib, and unblock dynamic-resource-allocation feature, and have the existing function calls tested with Rib to follow the new syntax.  
I gave it some thoughts if I could do it in the best possible way within a day of time, before deciding to make this particular PR (which is not the best possible way).  The thoughts are tangible, but very raw documentations here mainly for myself: https://www.notion.so/golemcloud/Rib-Supporting-New-Function-Syntax-ed92a3f1b92e4dd2a768402127f9aa7f. I would like to continue with this as a separate work
The only function syntax Rib tested ever was of the structure `namespace:package/interface/function-name(param1, param2)`, or simple `function-name(param1, …

Fix API gateway to follow the same function syntax that worker service expets

---

Cargo.lock
golem-worker-executor-base/Cargo.toml
golem-worker-executor-base/config/worker-service.toml
golem-worker-executor-base/src/services/golem_config.rs
golem-worker-executor-base/tests/lib.rs
golem-worker-executor-base/tests/measure_test_component_mem.rs

Resolves #612 
Contains an ignored test that was used to gather measurement data. We should never run it as a test, but it may be useful for further experiments on our test components.
Plot:
Results:
```
auction.wasm: component size: 80.77 KiB, avg delta memory: 248 KiB
auction_registry_composed.wasm: component size: 201.93 KiB, avg delta memory: 912 KiB
blob-store-service.wasm: component size: 61.83 KiB, avg delta memory: 320 KiB
c-1.wasm: component size: 59.56 KiB, avg delta memory: 141.33 KiB
caller_composed.wasm: component size: 203.62 KiB, avg delta memory: 437.33 KiB
child_component.wasm: component size: 2.56 MiB, avg delta memory: 8.16 MiB
clock-service.wasm: component size: 59.36 KiB, avg delta memory: 216 KiB
clocks.wasm: component size: 91.94 KiB, avg delta memory: 352 KiB …
```

Measure test component memory

---

golem-worker-service-base/src/worker_bridge_execution/refined_worker_response.rs

A hot fix to remove the following issue #641 
```
Internal Error. WorkerBridge expects the result from worker to be a Record if results are named
```
I am sorry I can't figure out why there was an empty check that existed before. By removing this it aligns with what wasm-rpc code base is doing
https://github.com/golemcloud/wasm-rpc/blob/main/wasm-rpc/src/json.rs#L118
This is mainly around avoid responses that are always wrapped in a vector.

Hot fix: Remove empty check as it is not done in wasm rpc code

---

golem-common/src/config.rs
golem-component-compilation-service/src/config.rs
golem-component-service/src/config.rs
golem-shard-manager/src/shard_manager_config.rs
golem-worker-executor-base/src/services/golem_config.rs
golem-worker-service/src/config.rs

Resolves #571 
- Fixes how config errors are displayed
- Makes sure to fail if the service's `toml` config is not found
Before:
```
thread 'main' panicked at /Users/vigoo/projects/ziverge/golem-services/golem-common/src/config.rs:122:38:
Failed to load config: Error { tag: Tag(Default, 2), profile: Some(Profile(Uncased { string: "default" })), metadata: Some(Metadata { name: "TOML file", source: Some(File("/Users/vigoo/projects/ziverge/golem-services/golem-worker-executor/config/worker-executor.toml")), provide_location: Some(Location { file: "/Users/vigoo/projects/ziverge/golem-services/golem-common/src/config.rs", line: 83, col: 14 }), interpolater:  }), path: ["active_workers", "drop_when_full"], kind: InvalidType(Str("xx"), "f64"), prev: None }
stack backtrace:
0: rust_begin_unwind
at …
```

Fix config error handling

---

Cargo.lock
golem-worker-executor-base/Cargo.toml
golem-worker-executor-base/src/services/oplog/primary.rs

Small fix for the path of external oplog payloads, the original intention was to use `md5hash-in-hex/uuid` but the implementation was creating paths like `[0C, 7B, 41, 17, C8, 01, 2C, 6D]/5AF2838B-B5A9-480E-BA6A-5610E32AA9E4`.

Fix external oplog payload blobstore path

---

integration-tests/tests/sharding.rs

Disable some sharding tests to avoid timeouts, planned to be fixed in https://github.com/golemcloud/golem/pull/690

Disable some sharding tests

---

golem-worker-service-base/src/repo/api_definition.rs
golem-worker-service-base/tests/services_tests.rs

Closes https://github.com/golemcloud/golem/issues/637
Propagates the rows affected as the boolean condition in ApiDefinitionRepo

API Definition Deletion Fix

---

golem-cli/src/clients/component.rs
golem-cli/src/clients/worker.rs
golem-cli/src/command.rs
golem-cli/src/command/component.rs
golem-cli/src/command/worker.rs
golem-cli/src/model.rs
golem-cli/src/model/component.rs
golem-cli/src/model/text.rs
golem-cli/src/oss/clients/component.rs
golem-cli/src/oss/clients/worker.rs
golem-cli/src/oss/command.rs
golem-cli/src/oss/main.rs
golem-cli/src/service/component.rs
golem-cli/src/service/worker.rs
golem-cli/tests/api_definition.rs
golem-cli/tests/api_deployment.rs
golem-cli/tests/cli.rs
golem-cli/tests/component.rs
golem-cli/tests/get.rs
golem-cli/tests/main.rs
golem-cli/tests/text.rs
golem-cli/tests/worker.rs
golem-common/src/uri/mod.rs
golem-common/src/uri/oss/mod.rs
golem-common/src/uri/oss/uri.rs
golem-common/src/uri/oss/url.rs
golem-common/src/uri/oss/urn.rs

New command - `top level get`:
```
golem-cli get component:///component_name
golem-cli get urn:component:c201c162-fd68-4750-9e7b-9aee8993beff
golem-cli get worker:///component_name/worker_name
golem-cli get urn:worker:c201c162-fd68-4750-9e7b-9aee8993beff/worker_name
golem-cli get api-definition:///definition_name/0.1.0
golem-cli get api-deployment:///example.com
```
This also works for consistency, but I'm not going to put it to the docs:
```
golem-cli get urn:api-definition:definition_name/0.1.0
golem-cli get urn:api-deployment:example.com
```
`component` and `worker` commands accept `URI` instead of ID:
```
golem-cli component get --component-name component_name
golem-cli component get --component component:///component_name
golem-cli component get --component …
```

518 golem URI

---

Cargo.lock
golem-cli/Cargo.toml
golem-cli/src/clients/worker.rs
golem-cli/src/command/api_definition.rs
golem-cli/src/command/component.rs
golem-cli/src/command/worker.rs
golem-cli/src/init.rs
golem-cli/src/model.rs
golem-cli/src/oss/clients/worker.rs
golem-cli/src/oss/command.rs
golem-cli/src/oss/main.rs
golem-cli/src/service/worker.rs

- Integrates the `new` command improvements implemented in https://github.com/golemcloud/golem-examples/pull/44
- Adds a few command aliases (Resolves #700)
- Uses clap argument groups where possible, which provides better `--help` output for alternatives
- Adds the missing `worker resume` command
Examples of how argument groups improve the help output:
```
Usage: golem-cli worker invoke [OPTIONS] --worker <URI> --component <URI> --component-name <COMPONENT_NAME> --worker-name <WORKER_NAME> --function <FUNCTION> <--json <json>|--arg <wave>>
Usage: golem-cli component update [OPTIONS] <--component <URI>|--component-name <COMPONENT_NAME>> <component-file>
```
Previously these alternatives (`<...|...>`) were not printed

A set of CLI improvements

---

.github/workflows/ci.yaml
Cargo.lock
golem-common/src/model/oplog.rs
golem-worker-executor-base/src/durable_host/mod.rs
golem-worker-executor-base/src/invocation.rs
golem-worker-executor-base/src/model.rs
golem-worker-executor-base/src/worker.rs
golem-worker-executor-base/tests/api.rs
golem-worker-executor-base/tests/wasi.rs

Resolves #693 
- Skip hint entries when calculating retry count (the number of errors at the end of the oplog) as they can interleave the errors (example: new incoming invocation)
- Not writing resource create/describe/drop entries in reply mode (this with the lack of the first point caused the infinite retry loop)
- Fixes an issue where a worker ends up idle when invoked with a non-existing function, as the error was returned earlier than writing the bad invocation to the oplog.

Fix worker infinite retry

---

golem-cli/src/command/component.rs
golem-cli/src/service/component.rs
golem-cli/src/service/deploy.rs
golem-cli/src/service/worker.rs

Resolves #699 
Small convenience feature that allows fallback `component update` to add and `component add` to update, only in `text` mode.
Note that the "error matching" is ugly (string based) but I did not want to do bigger changes now in error handling.

Convenience fallback mode for component add and update

---

golem-worker-executor-base/src/durable_host/golem/mod.rs

This makes the worker executor immediately commit the oplog when the idempotency key is generated.

Change generate_idempotency_key function type to commit immediately

---

golem-cli/src/command/profile.rs
golem-cli/src/init.rs
golem-cli/src/main.rs
golem-cli/src/oss/main.rs

Allow Golem Cloud to configure profile authentication process for `golem-cli init` command

fix profile auth

---

Cargo.lock
golem-rib/src/compiler/byte_code.rs
golem-rib/src/compiler/ir.rs
golem-rib/src/compiler/type_with_unit.rs
golem-rib/src/inferred_type.rs
golem-rib/src/interpreter/rib_interpreter.rs
golem-worker-service-base/src/worker_service_rib_interpreter/mod.rs

Making sure, given a function `foo` that returns `unit`, it responds with a http response with empty body.
Handling `Unit` was done before, and therefore this is more of a bug fix,  with more tests at worker-service side which decides what to do with a result from `golem-rib` that can either be a `Unit` or `TypeAnnotatedValue`
Following is possible
```scala
// foo returns unit
let x = foo("bar");
x
```
This will return a response with empty response body. I think we cannot expect the user to never use the result from a function which was `Unit`. Intuitively,
```scala
foo("bar")
```
is isomorphic to
```
let x = foo("bar");
x
```

Fix unit returns

---

golem-cli/src/command/component.rs
golem-cli/src/service/component.rs

Resolves https://github.com/golemcloud/golem-cloud/issues/1467
Fixes and cleans up the --non-interactive flag for component update and add, and also returns the appropriate result based on the actual operation performed

Fix golem-cli add and update --non-interactive

---

golem-api-grpc/build.rs
golem-api-grpc/proto/golem/rib/expr.proto
golem-api-grpc/proto/golem/rib/type_name.proto
golem-cli/tests/api_definition.rs
golem-rib/src/compiler/byte_code.rs
golem-rib/src/compiler/desugar.rs
golem-rib/src/compiler/mod.rs
golem-rib/src/expr.rs
golem-rib/src/inferred_type.rs
golem-rib/src/parser/let_binding.rs
golem-rib/src/parser/mod.rs
golem-rib/src/parser/type_binding.rs
golem-rib/src/parser/type_name.rs
golem-rib/src/text/mod.rs
golem-rib/src/text/writer.rs
golem-rib/src/type_inference/expr_visitor.rs
golem-rib/src/type_inference/identifier_inference.rs
golem-rib/src/type_inference/mod.rs
golem-rib/src/type_inference/name_binding.rs
golem-rib/src/type_inference/pattern_match_binding.rs
golem-rib/src/type_inference/type_pull_up.rs
golem-rib/src/type_inference/type_unification.rs
golem-worker-service-base/src/http/http_request.rs
golem-worker-service-base/src/worker_service_rib_interpreter/mod.rs
golem-worker-service-base/tests/services_tests.rs

The PR is not showing enough changes since the base branch is https://github.com/golemcloud/golem/pull/822, however shows the fundamental logic addition and test changes  (that verifies the change) for easier review.
* Able to specify if there is an ambiguity in types (type annotation), as our stack based interpreter needs to know the actual types and cannot guess (we made some hacks during release 1.0 such as fall back to u64 if user specified a number which can be u8, u16 etc but this leads to a lot of corner cases, and we decided to take this path). Example returning an `empty list` is never possible without this strategy.
```scala
let my_list: list<u8> = [];
{status: 200, body: my_list}
```
* There is no need to specify the type if it can infer from any function calls to worker. The …

Type binding

---

golem-common/src/tracing.rs
golem-test-framework/src/components/k8s.rs
integration-tests/src/benchmarks/mod.rs
integration-tests/tests/lib.rs
integration-tests/tests/sharding.rs

https://github.com/mmastrac/rust-ctor/issues/307
seems to be caused by using std::io output

Fix ctor std thread init

---

golem-api-grpc/proto/golem/rib/expr.proto
golem-api-grpc/proto/golem/rib/ir.proto
golem-rib/src/call_type.rs
golem-rib/src/compiler/byte_code.rs
golem-rib/src/compiler/ir.rs
golem-rib/src/expr.rs
golem-rib/src/inferred_type.rs
golem-rib/src/interpreter/rib_interpreter.rs
golem-rib/src/interpreter/stack.rs
golem-rib/src/parser/pattern_match.rs
golem-rib/src/type_inference/enum_resolution.rs
golem-rib/src/type_inference/mod.rs
golem-rib/src/type_inference/variant_resolution.rs
golem-rib/src/type_registry.rs

Support Enums in Rib, and add the ability to compile variants with hyphens in their names.

---

golem-cli/src/config.rs
golem-cli/src/factory.rs
golem-cli/src/lib.rs
golem-cli/src/main.rs
golem-cli/src/oss/factory.rs
golem-cli/src/oss/main.rs
golem-cli/src/service/version.rs
golem-cli/src/service/worker.rs

golem cli changes:
- use the same reqwest client for all request to reuse tcp connections, and init them at factory creation -> no need for error handling during context and service creation
- use Arc for reused clients / services, cleanup async usages and internal client builders
- remove non used (in oss) auth parts
- extract as public more common parts with cloud (make reqwest client, init tracing, version check)
- version check cleanups
- separate health check call errors and version mismatch
- make cli_version an argument, so it is not tied to the oss lib / cli version
- only do health check / version requests for unique urls, and do them in parallel
- change the message from cargo install to point to binary releases and to docs
- cleanup http config, separate env vars for normal and …

Gloem-cli perf opt and service factory refactor

---

golem-rib/src/expr.rs
golem-rib/src/parser/binary_comparison.rs
golem-rib/src/parser/boolean.rs
golem-rib/src/parser/call.rs
golem-rib/src/parser/cond.rs
golem-rib/src/parser/errors.rs
golem-rib/src/parser/flag.rs
golem-rib/src/parser/identifier.rs
golem-rib/src/parser/let_binding.rs
golem-rib/src/parser/literal.rs
golem-rib/src/parser/mod.rs
golem-rib/src/parser/multi_line_code_block.rs
golem-rib/src/parser/not.rs
golem-rib/src/parser/number.rs
golem-rib/src/parser/optional.rs
golem-rib/src/parser/pattern_match.rs
golem-rib/src/parser/record.rs
golem-rib/src/parser/result.rs
golem-rib/src/parser/rib_expr.rs
golem-rib/src/parser/select_field.rs
golem-rib/src/parser/select_index.rs
golem-rib/src/parser/sequence.rs
golem-rib/src/parser/tuple.rs
golem-rib/src/parser/type_name.rs
golem-worker-service-base/src/worker_service_rib_interpreter/mod.rs

For an invalid syntax such as the following:
```rust
match foo
ok(x) => x,
err(x) => x
}
```
Main branch behaviour:
```scala
Failed to parse: "${match request.id ok(x) => x, err(x) => x }}"
```
```scala
Parse error at line: 2, column: 1
Unexpected `o`
Expected whitespace or `{`
Invalid syntax for pattern match
```
* Points to the exact line number and column number using Stream Input `position::Stream`
* Better errors (as much as possible). There are corner cases or ambiguous cases such as an invalid expression  `{a` could be  a flag or a record, and it cannot say the exact error but just saying `missing :` or `missing }` in specific location in the code. Also I am stopping it here as this is far better than what we have in main branch.
* Proper use of `eof` instead of partial parsing and …

Precise Rib Parsing & Errors

---

golem-rib/src/parser/binary_comparison.rs
golem-rib/src/parser/boolean.rs
golem-rib/src/parser/call.rs
golem-rib/src/parser/cond.rs
golem-rib/src/parser/errors.rs
golem-rib/src/parser/flag.rs
golem-rib/src/parser/identifier.rs
golem-rib/src/parser/let_binding.rs
golem-rib/src/parser/literal.rs
golem-rib/src/parser/multi_line_code_block.rs
golem-rib/src/parser/not.rs
golem-rib/src/parser/number.rs
golem-rib/src/parser/optional.rs
golem-rib/src/parser/pattern_match.rs
golem-rib/src/parser/record.rs
golem-rib/src/parser/result.rs
golem-rib/src/parser/rib_expr.rs
golem-rib/src/parser/select_field.rs
golem-rib/src/parser/select_index.rs
golem-rib/src/parser/sequence.rs
golem-rib/src/parser/tuple.rs
golem-rib/src/parser/type_name.rs

Fixes #943 
Given below are some examples showing how this PR improved/fixed Rib behaviour from a user perspective
* `let let = 1;` was allowed before. This is not allowed anymore.
* `{ err : "foo" }` wasn't allowed before. Now we allow it! Field names can be `err`, or `ok` or such keywords. The idea here is names in `record` are more-or-less text itself. The only difference is they are not wrapped in `quotes` following WASM-WAVE syntax.
* `some1((x)` wasn't allowed before.  Likewise `err1`, `none1`, `match1` etall used to fail. Obviously users can write their own variants having such names. 
* Proper Custom Error called `RibParseError` which can be used only if there is constraints that talks about conversion to combine's native StreamError. This is a very nice feature in combine, that …

Explicit RibParseError, avoid `expect`s in parsers and handle keywords properly

---

Cargo.lock
Cargo.toml
golem-cli/Cargo.toml
golem-worker-executor-base/src/services/oplog/mock.rs
golem-worker-executor-base/src/services/oplog/mod.rs
golem-worker-executor-base/src/services/oplog/multilayer.rs
golem-worker-executor-base/src/services/oplog/primary.rs
golem-worker-executor-base/src/services/oplog/tests.rs
golem-worker-executor-base/src/services/scheduler.rs
golem-worker-executor-base/src/services/worker.rs
golem-worker-executor-base/src/worker.rs

If a set of conditions were met:
- All entries of the oplog were moved to archive layers from the primary oplog
- All in-memory oplog related instances for the given worker were already dropped from all caches
- The worker is reopened by some new invocation or update request
It could happen that the newly opened oplog used a wrong view of what the "last oplog index" is (only looking at the primary layer), and then the next written entry gets the wrong identifier (`1`). As this (and many following) index is already used and is stored in one of the archive layers, this becomes a corrupt oplog leading to many unexpected issues.
This pull request:
- Provides a test that reproduced the issue and proves the fix
- Fixes the root cause
- Reduces the effect of trying to open such a corrupt oplog, …

Tests and fixes for oplog corruption bug

---

golem-worker-executor-base/src/lib.rs
golem-worker-executor-base/src/metrics.rs
golem-worker-executor-base/src/services/scheduler.rs
golem-worker-executor-base/src/services/worker.rs

Remove cached worker status when a worker oplog is fully archived

---

golem-rib/src/expr.rs
golem-rib/src/interpreter/tests/mod.rs

A small follow up PR on https://github.com/golemcloud/golem/commit/1b0902a5de687fc1bbb402adcfd3d5012e912bf1
* Custom message for assertion with textual representation of type annotated value to make debugging easier
* Expand the comprehensive test with `err` pattern match. No bugs captured with this expansion but its important to cover as much as possible. We will be continuing to do this.
* Remove `unwrap` from `or` helper constructor. It looks like this constructor was never used.

Expand comprehensive test with `err`

---

golem-component-service/db/migration/sqlite/002__add_component_type.sql

Sqlite does not support "IF NOT EXISTS", and we do have a migration table for checks, so let's drop it.

Fix component-service "add component type" sqlite migration

---

Cargo.toml
golem-cli/Cargo.toml
golem-cli/tests/worker.rs
golem-common/src/model/exports.rs
golem-common/src/model/public_oplog.rs
golem-worker-executor-base/src/model/public_oplog/mod.rs
golem-worker-executor-base/tests/api.rs
golem-worker-executor-base/tests/observability.rs
integration-tests/tests/worker.rs

Resolves https://github.com/golemcloud/golem/issues/1007
- Fixes some issues with the serialization of public oplog entries and the interpretation of the payloads
- Integrates https://github.com/golemcloud/wasm-rpc/pull/94
- Adds oplog query to more integration tests to cover more cases
- Stabilizes the flaky oplog enumeration tests

Fixes and tests for oplog enumeration

---

golem-rib/src/expr.rs
golem-rib/src/parser/block.rs
golem-rib/src/parser/block_without_return.rs
golem-rib/src/parser/list_aggregation.rs
golem-rib/src/parser/list_comprehension.rs
golem-rib/src/parser/literal.rs
golem-rib/src/parser/mod.rs
golem-rib/src/parser/rib_expr.rs

In response to https://discord.com/channels/1134448700572319785/1134448701260169249/1300769907755061268
**_and tracked as part of https://github.com/golemcloud/golem/issues/1035 which is currently in progress_**
Previously I  tested the html str responded from worker, however, not inlining HTML within Rib. Things failed when inlining within a string interpolation, as indicated by discord user.
```scala
let style = "font-family: Arial, sans-serif; display: flex; align-items: center; justify-content: center; height: 100vh; background: linear-gradient(135deg, #1e3c72, #2a5298); color: #ffffff; text-align: center; padding: 20px;";
let user: u64 = request.path.user-id;
let body = "
<!DOCTYPE html>
<html>
<head>
</head>
<body style='${style}'>
<div>
<h1>Welcome to Golem Cloud!</h1>
<p …
```

Make string interpolation flexible

---

Cargo.lock
golem-cli/src/clients/api_definition.rs
golem-cli/src/command/api_definition.rs
golem-cli/src/model.rs
golem-cli/src/oss/clients/api_definition.rs
golem-cli/src/service/api_definition.rs
golem-cli/tests/api_definition.rs
golem-cli/tests/api_deployment.rs
golem-cli/tests/get.rs
golem-cli/tests/text.rs
golem-client/Cargo.toml
golem-common/Cargo.toml
golem-common/src/json_yaml.rs
golem-common/src/lib.rs
golem-worker-service-base/src/api/register_api_definition_api.rs
golem-worker-service-base/src/api_definition/http/http_oas_api_definition.rs
golem-worker-service/src/api/api_definition.rs
openapi/golem-service.yaml

TODO
```yaml
openapi: "3.0.0"
info:
title: "Sample API"
version: "1.0.3"
x-golem-api-definition-id: "myapi"
x-golem-api-definition-version: "0.1.1"
paths:
"/{user-id}/get-cart-contents":
x-golem-worker-bridge:
worker-name: "\"foo\""
component-id: "aae6dd36-8caa-4271-8ef3-cf1f88ef9c97"
component-version: 0
response: |
let style = "font-family: Arial, sans-serif; display: flex; align-items: center; 
justify-content: center; height: 100vh; background: linear-gradient(135deg, 
#1e3c72, #2a5298); color: #ffffff; text-align: center; padding: 20px;";
let user: u64 = request.path.user-id;
{
Content-Type: "text/html",
status: 200u64,
body: "<!DOCTYPE html><html><head></head><body style='${style}'>
<div><h1>Welcome to Golem Cloud!</h1>
<p style='font-size: 1.5em;'>Hello, User ID: ${user}</p>
<p …
```

Yaml support for API definition

---

golem-common/src/model/plugin.rs
golem-component-service-base/src/service/component.rs
golem-component-service-base/src/service/plugin.rs
golem-component-service/src/api/component.rs
golem-component-service/src/api/mod.rs
golem-component-service/src/grpcapi/component.rs
golem-component-service/src/grpcapi/mod.rs

Verify plugin scopes on installation

---

.github/workflows/ci.yaml
golem-component-compilation-service/docker/Dockerfile
golem-component-service/docker/Dockerfile
golem-shard-manager/docker/Dockerfile
golem-worker-executor/docker/Dockerfile
golem-worker-service/docker/Dockerfile

- added `pkg-config` to try to solve the problem with `openssl-sys` crate
- added `libfontconfig1-dev` just to be sure based on Kaur's comment in the other PR :)

Try to fix docker builds

---

golem/src/command.rs
golem/src/launch.rs
golem/src/proxy.rs

**Goal:** Allow customization of Golem server address.
**Usage:**
```bash
$ golem start --router-addr 192.168.1.1
```

Parametrize bind address of local Golem server

---

golem-test-framework/src/components/component_service/filesystem.rs

Fix win build (apart from golem bin)

---

Cargo.lock
golem-cli/Cargo.toml
golem-cli/src/command.rs
golem-cli/src/diagnose.rs
golem-cli/src/examples.rs
golem-cli/src/model.rs
golem-cli/src/model/text.rs
test-components/auction-example/auction-registry/golem.yaml
test-components/auction-example/auction/golem.yaml
test-components/auction-example/golem.yaml
test-components/rpc/caller/golem.yaml
test-components/rpc/counters/golem.yaml
test-components/rpc/ephemeral/golem.yaml
test-components/rpc/golem.yaml
test-components/rust-service/rpc/child-component/golem.yaml
test-components/rust-service/rpc/golem.yaml
test-components/rust-service/rpc/parent-component/golem.yaml
test-components/ts-rpc/caller/golem.yaml
test-components/ts-rpc/counter/golem.yaml
test-components/ts-rpc/golem.yaml
wasm-rpc-stubgen/src/commands/app.rs
wasm-rpc-stubgen/src/lib.rs
wasm-rpc-stubgen/src/log.rs
wasm-rpc-stubgen/src/model/app.rs

- update app manifest schema refs
- update golem-examples
- add `new-app-component` (for now added a root command, during the Cli Manifest Refactor we will move this to a better place, but that will involve more refactors around how commands are nested)
- extended the dynamic help for `golem-cli app` to include component info
`golem-cli app` in project root folder |  `golem-cli app` in ts folder with release profle
:-------------------------:|:-------------------------:

Update for composable app manifests

---

golem-component-compilation-service/docker/Dockerfile
golem-component-service/docker/Dockerfile
golem-shard-manager/docker/Dockerfile
golem-worker-executor/docker/Dockerfile
golem-worker-service/docker/Dockerfile

Fixing
```
(Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgres-1                             | 2025-01-21 13:22:53.444 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-1                             | 2025-01-21 13:22:53.444 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-1                             | 2025-01-21 13:22:53.460 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1                             | 2025-01-21 13:22:53.471 UTC [29] LOG:  database system was shut down at 2025-01-21 13:22:48 UTC
postgres-1                             | 2025-01-21 13:22:53.482 UTC [1] LOG:  database system is ready to accept connections
golem-shard-manager-1                  | ./golem-shard-manager: /lib/x86_64-linux-gnu/libm.so.6: …
```

Use ubuntu latest in docker

---

golem-rib/src/compiler/byte_code.rs
golem-rib/src/interpreter/interpreter_stack_value.rs
golem-rib/src/interpreter/literal.rs
golem-rib/src/interpreter/rib_interpreter.rs
golem-rib/src/interpreter/stack.rs
golem-rib/src/interpreter/tests/mod.rs

Certain `value_and_type`s were referred as `type_annotated_value`. Fixing them before other upcoming changes

Rename type_annotated_value to value_and_type

---

golem-rib/src/parser/call.rs

Resolves #1348 
Can't stop myself from saying this: It took 30 mins to understand what to do with associative error types and subtle `From` `to` conversions within library to write 2 lines.

Avoid panic in function name parser when parsing individual resource parameters

---

golem-service-base/src/headers.rs
golem-worker-executor-base/src/durable_host/http/mod.rs
golem-worker-executor-base/src/durable_host/http/outgoing_http.rs
golem-worker-executor-base/src/durable_host/http/serialized.rs
golem-worker-executor-base/src/durable_host/mod.rs

Resolves #1333 
- Starts a span with uri/method information for outgoing wasi-http requests
- Finishes the span when the request is dropped
- Adds the trace-context headers to the outgoing request if this option is enabled (way to change the option will come in a follow-up PR when host functions are added)

Add a span for outgoing http requests and add trace context headers

---

golem-common/src/metrics.rs
golem-component-compilation-service/src/grpc.rs
golem-component-service-base/src/api/common.rs
golem-component-service/src/api/mod.rs
golem-component-service/src/lib.rs
golem-shard-manager/src/error.rs
golem-worker-executor-base/src/error.rs
golem-worker-service-base/src/api/common.rs
golem-worker-service-base/src/api/error.rs
golem-worker-service-base/src/service/worker/default.rs
golem-worker-service-base/src/service/worker/routing_logic.rs
golem-worker-service/src/lib.rs

Resolves #1354 
- Removes the poem tracing and logging middlewares because they were redundant (we already had our own `recorded_http_api` stuff, and that one contains more information)
- Removes redundant log lines from the worker service
- Introduces the concept of "expected" failures which are not logged as errors (still logged but on info level). An example is "worker not found" 
With these changes completely normal things like a user trying to get a non-existing worker's metadata are not resulting in multiple error lines in the logs.

No error on nonexisting worker

---

golem-worker-service-base/src/gateway_execution/file_server_binding_handler.rs
golem-worker-service-base/src/gateway_execution/gateway_http_input_executor.rs
golem-worker-service-base/src/gateway_execution/http_handler_binding_handler.rs
golem-worker-service-base/src/gateway_execution/mod.rs
golem-worker-service-base/tests/api_gateway_end_to_end_tests.rs

Slightly different than what we discussed, but I believe this way it's fully consistent with other binding types

Use latest component version to retrieve files if there is no worker

---

golem-worker-service-base/src/gateway_execution/gateway_http_input_executor.rs
golem-worker-service-base/src/gateway_execution/request.rs
golem-worker-service-base/src/gateway_rib_compiler/mod.rs
golem-worker-service-base/tests/api_gateway_end_to_end_tests.rs
integration-tests/tests/api/api_deployment.rs
wasm-rpc/src/json/impl.rs

The changes are small, but these are some fundamental changes in my view - and very important. 
* Look up query or path or headers only if needed by the Rib script. Not for every http request. Infact, look up from `poem::Request` for specific header keys that are _required_ and transform/parse them specifically, instead of collecting everything together.
* Make sure if a number is passed in path or query, but rib expects a string (which by default expects string for these global paths except body), it should work. I think this might be a regression and the lack of tests in this space need to be fixed
* Better error messages. Such as instead of `invalid request. expected : record { headers: {user-id: string} }`, with this PR, it will be `missing header: user-id`.  Bring back more details …

Fix query params and avoid redundant lookups in hot path

---

golem-worker-service-base/src/gateway_execution/gateway_http_input_executor.rs
golem-worker-service-base/src/gateway_execution/request.rs
golem-worker-service-base/src/gateway_execution/to_response.rs
golem-worker-service-base/tests/api_gateway_end_to_end_tests.rs

* The code still ensures that we don't consume request body if unused in any rib script. So this is _NOT_ early consumption and reuse across
* If API definition has multiple rib scripts exists that needs to look up request body (ending up resulting in consuming request body from poem::Request), it should still behave lazy (i.e, only if its used) and yet reuse, avoiding potentially "empty" body errors.

Make sure request body can be used in multiple rib scripts (if any) within one request

---

golem-worker-executor-base/src/worker/mod.rs

This is a simple fix for the issue reported about `unwrap()` panicking when trying to automatically update a worker.
The fix is just to simply ignore this error - because the only way it can fail is if the receiver of this channel is already being dropped, which means the run loop has quit anyway; this is basically the same effect we want from the interruption (stop the running worker so we can update it) so we can safely ignore it.

Attempt to fix a race condition when interrupting workers for update

---

golem-test-framework/src/dsl/mod.rs
golem-worker-executor-base/src/model/public_oplog/mod.rs
golem-worker-executor-base/tests/blobstore.rs
golem-worker-executor-base/tests/guest_languages1.rs
golem-worker-executor-base/tests/guest_languages2.rs
golem-worker-executor-base/tests/guest_languages3.rs
golem-worker-executor-base/tests/hot_update.rs
golem-worker-executor-base/tests/keyvalue.rs
golem-worker-executor-base/tests/observability.rs
golem-worker-executor-base/tests/rdbms.rs
golem-worker-executor-base/tests/revert.rs
golem-worker-executor-base/tests/rust_rpc.rs
golem-worker-executor-base/tests/rust_rpc_stubless.rs
golem-worker-executor-base/tests/transactions.rs
golem-worker-executor-base/tests/ts_rpc1_stubless.rs
golem-worker-executor-base/tests/ts_rpc2_stubless.rs
golem-worker-executor-base/tests/wasi.rs

As I could not reproduce #1493 I added more tests for oplog query (into each worker executor test) and found an issue with RPC invocation encoding which is fixed in this PR (and kept backward compatible with older oplog entries too)

Test oplog query in all worker executor tests, and one fix

---

golem-rib/src/function_name.rs
golem-rib/src/parser/call.rs

Fixes `ParsedFunctionName::parse`
- to consume the whole input, not returning false partial matches
- fixed missing support for "static method in indexed resource" syntax
Part of https://github.com/golemcloud/golem-cli/issues/190

Make sure ParsedFunctionName is not accepting partial matches

---

golem-rib/src/interpreter/rib_interpreter.rs
golem-rib/src/interpreter/stack.rs
golem-rib/src/type_inference/type_pull_up.rs

Fixes #1047  #1462 
In short, with this PR the following works (previously it will throw run time error if you try to interpolate a record)
```rust
let x = "foo";
let y = "bar";
let z = {foo: "baz"};
let n: u32 = 42;
let result = "${x}-${y}-${z}-${n}";
result
```
will result in the following, where each value is a wasm-wave string.
```
"foo-bar-{foo: baz}-42"
```
The ticket 1462 says to allow only literals, but here _literals_ mainly intend to mean - anything that can be _safely_ interpolated. In that case, `enums`  or primitives (number, string, char) and interestingly developers may want to stringify a no-arg variant term too (whose value can be sometimes available only at runtime disallowing a compile time check as to whether or not a particular variant value is amongst the ones with …

allow string concatenation with any type

---

golem-test-framework/src/dsl/mod.rs
golem-worker-executor-base/src/model/mod.rs
golem-worker-executor-base/src/worker/invocation.rs
golem-worker-executor-base/tests/api.rs

This makes it behaving the same as invalid function names - the worker remains usable after, and nothing is written to the oplog.
This also explains and fixes the revert related linked issue.
Resolves #1498

Fix how invalid parameters are handled in worker executor

---

golem-test-framework/src/components/worker_service/mod.rs
golem-worker-service-base/src/api/api_definition.rs
golem-worker-service-base/src/gateway_api_definition/http/api_definition.rs
golem-worker-service-base/src/gateway_api_definition/http/api_definition_request.rs
golem-worker-service-base/src/gateway_api_definition/http/oas_api_definition.rs
golem-worker-service-base/src/gateway_api_definition_transformer/cors_transformer.rs
golem-worker-service-base/src/gateway_execution/gateway_http_input_executor.rs
golem-worker-service-base/src/gateway_middleware/http/cors.rs
golem-worker-service-base/src/gateway_middleware/http/http_middleware.rs
golem-worker-service-base/src/gateway_middleware/http/middleware_error.rs
golem-worker-service-base/src/gateway_middleware/mod.rs
golem-worker-service-base/tests/api_gateway_end_to_end_tests.rs

This is in-progress (this is not code refactor, but main intention is to make peripherals easier to understand and thereby make DX integration easier)
Code evaluation and simplifying certain fields to make DX integration easier
* Fixing comments about the fields in gateway binding fields. I will be adding more documentation here.
* Removing unused (unused after https://github.com/golemcloud/golem/pull/1444) on CORS in the request front-end data. 
* Removing redundant `cors` field anywhere else too (such as within the binding, and outside the binding, there was CORS - probably making it closer to OAS - but this is not needed in native API definition. This can be removed.
* (Yet to be done) Removing higher level security field to match Open API Specific format, where securities are listed …

clean ups in API definition (for CORS and security) - to make DX integration easier

---

golem-rib-repl/src/compiler.rs
golem-rib-repl/src/dependency_manager.rs
golem-rib-repl/src/invoke.rs
golem-rib-repl/src/lib.rs
golem-rib-repl/src/rib_edit.rs
golem-rib-repl/src/rib_repl.rs
golem-rib/src/compiler/mod.rs
golem-rib/src/instance_type.rs
golem-rib/src/type_registry.rs
integration-tests/src/rib_repl/bootstrap.rs
integration-tests/src/rib_repl/main.rs
integration-tests/tests/rib_repl.rs

Rib_Repl crate is succesfully [integrated](https://github.com/golemcloud/golem-cli/commit/bdb6f7d42ca8ecaa6a7e3dcf4828cf82ffb0e22a) and is running with CLI, however, we found a few (very) minor things. This PR mostly just addresses them, plus more features/fixes
* Function invoke  and component load implementation returns `anyhow::Result` instead of deciding it is always a `String`
* Adding component name in APIs along with ComponentId for logging purpose
* Display for ReplBootstrapError (currently CLI uses debug)
* This wasn't spotted, but fixed the imports: Example: `golem_rib_repl::WorkerFunctionInvoke` instead of `golem_rib_repl::invoke::WorkerFunctionInvoke` - everything is under `golem_rib_repl`. 
* Extracted bootstrap parameters as RibReplConfig and added prompt as a config options …

Minor fixes on Repl APIs

---

golem-rib-repl/src/rib_edit.rs

Automatically completing variant arguments
With this everything in your WIT is auto completed with Repl. This auto completion is important across the board to reduce users face compile time errors, that they only need to edit the args everywhere.
https://github.com/user-attachments/assets/7a084857-a9e8-43d5-b96f-815fc145f5e6
This was for the following WIT
```
package pack:name;
interface component-name-api {
enum status {
backlog,
in-progress,
done,
}
enum priority {
low,
medium,
high,
}
enum query-sort {
priority,
deadline,
}
record new-item {
title: string,
priority: priority,
deadline: option<string>,
}
record update-item {
title: option<string>,
priority: option<priority>,
status: option<status>,
deadline: option<string>,
}
record item {
id: string,
title: string,
priority: priority, …
```

Auto completion of variant arguments

---

golem-rib/src/parser/record.rs
golem-rib/src/parser/rib_expr.rs
golem-worker-service-base/src/gateway_api_definition/http/path_pattern_parser.rs
golem-worker-service-base/tests/api_gateway_end_to_end_tests.rs
integration-tests/tests/api/api_deployment.rs

This change is based on some observations shared by @noise64

Handle query and path parameters with spaces in api gateway

---

golem-worker-service-base/tests/api_gateway_end_to_end_tests.rs

Fixes #1589 
Works as expected, and I am not sure during hackathon developer one of the users said that's not the case
Expanded an existing test case for this behaviour

Confirm request path, query and header values can be numbers while type requirement is string

---

.gitignore
Cargo.lock
cloud-service/Cargo.toml
cloud-service/tests/it_tests.rs

closes #1664 
Removed backtrace-on-stack-overflow and add golem-cloud-client/openapi to .gitignore 
Both `cargo make build ` and `cargo make fix` both now work in windows. 
Error is due to, Unit Test failing for a test in `worker-executor/worker/status`
`timestamp: Timestamp(Timestamp("2025-05-31T14:13:54.067000000Z")), ` vs 
`timestamp: Timestamp(Timestamp("2025-05-31T14:13:54.068000000Z")),`
Not sure why, should very likely be resolved if re-run.

Remove backtrace-on-stack-overflow and Minor changes to .gitignore 

---

golem-rib-repl/src/invoke.rs
golem-rib-repl/src/repl_state.rs
golem-rib/regression_tests/lib.rs
golem-rib/src/interpreter/env.rs
golem-rib/src/interpreter/rib_function_invoke.rs
golem-rib/src/interpreter/rib_interpreter.rs
golem-rib/src/interpreter/rib_runtime_error.rs
golem-worker-service-base/src/gateway_rib_interpreter/mod.rs
golem-worker-service-base/tests/api_gateway_end_to_end_tests.rs
integration-tests/src/rib_repl/bootstrap.rs
integration-tests/tests/rib_repl.rs

Raised against no-multi-return branch
This PR doesn't affect any other part of code other than golem-rib, repl, the tests in worker-service-base and will help continuing the original PR faster if this gets merged
The integration tests that are failing is already failing in https://github.com/golemcloud/golem/tree/no-multi-return and hence not touching them for now

make rib interpreter aware that the worker function invoke can return optional value handling `Unit` functions

---

golem-api-grpc/proto/golem/component/plugin_definition.proto
golem-api-grpc/proto/golem/component/v1/plugin_service.proto
golem-common/src/model/plugin.rs
golem-component-service/src/api/plugin.rs
golem-component-service/src/authed/plugin.rs
golem-component-service/src/error.rs
golem-component-service/src/grpcapi/plugin.rs
golem-component-service/src/service/component.rs
golem-component-service/src/service/plugin.rs
golem-test-framework/src/components/component_service/mod.rs
golem-test-framework/src/dsl/mod.rs
integration-tests/tests/api/plugins.rs
openapi/golem-component-service.yaml
openapi/golem-service.yaml

resolves #1756 
Plugins with component and project scope are now always owned by the account of the project / component.
Plugins with global scope can only be used in projects / components that are in the same account.
Had to remove a few routes that do not make sense / cannot be properly implemented with the cleaned up owners. Checked both the cli and console and they are not using them, so updates should be easy.

Improve plugin definition and installation in shared projects

---

cloud-service/src/api/project.rs
golem-component-service/db/migration/postgres/016__plugin_installation_pkey.sql
golem-component-service/db/migration/sqlite/014__plugin_installation_pkey.sql
golem-component-service/src/api/component.rs
golem-component-service/src/model/component.rs
golem-component-service/src/service/component.rs
integration-tests/tests/api/plugins.rs
openapi/cloud-spec.yaml
openapi/golem-component-service.yaml
openapi/golem-service.yaml

Regression cause by one of my previous PRs, also added regression test for it.
The problem was that I missed that plugin installations are supposed to change their IDs in a new component version even if the installation itself did not change.
While writing tests for this, I found the old behavior to be extremely difficult to work with (as you always need to query the latest component after each update and get the new ids), so I decided to change it to be inline with my previous misunderstanding.
The index is now on (installation_id, component_id, component_version) and the installation id does never change until a plugin is uninstalled from a component.

Fix plugin installation id regeneration during batch plugin installation update

---

local-run/nginx.conf

localhost in the upstream caused it to try to connect with both ipv4 and ipv6, while our service only listened on ipv4.

Update nginx config to avoid connection issues

---

golem-router/golem-services.conf.template

port fix for default route
docker compose startup failing on error
```
2025/07/29 11:48:41 [emerg] 1#1: invalid port in upstream "golem-component-service:" in /etc/nginx/nginx.conf:47
nginx: [emerg] invalid port in upstream "golem-component-service:" in /etc/nginx/nginx.conf:47
```

golem-router - port fix

---

.github/workflows/ci.yaml

This may make the docker publish step of CI faster

Use blacksmith's build-push-action instead of the default one

---

golem-common/src/base_model.rs
golem-debugging-service/src/auth.rs
golem-debugging-service/src/config.rs
golem-debugging-service/src/debug_context.rs
golem-debugging-service/src/debug_session.rs
golem-debugging-service/src/jrpc.rs
golem-debugging-service/src/model/params.rs
golem-debugging-service/src/services/debug_service.rs
golem-debugging-service/tests/debug_mode/dsl.rs
golem-debugging-service/tests/debug_tests.rs
golem-debugging-service/tests/regular_mode/worker_ctx.rs
golem-worker-executor/src/durable_host/mod.rs
golem-worker-executor/src/durable_host/replay_state.rs
golem-worker-executor/src/worker/invocation_loop.rs
golem-worker-executor/src/worker/mod.rs
golem-worker-executor/src/workerctx/cloud.rs
golem-worker-executor/src/workerctx/mod.rs
golem-worker-executor/tests/common/mod.rs

resolves #1855 
Changes:
* time_out_in_seconds parameter is removed. All commands will deterministically wait exactly as long as needed
success response field removed (it was always true anyway)
* playback now doesn't always restore the worker from the beginning. Instead the behaviour depends on the position at which a worker stopped. If it stopped at an invocation boundary (for example by passing ensure_invocation_boundary), it will only do an incremental replay between the previous index and the current index. If it stopped in the middle of an invocation we need to do a full replay from the beginning (due to the mechanism that is used to stop workers in the middle of an invocation)
* There is now a incremental_playback boolean field in the playback response. This communicates which …

Fix bug with debugging indices and improve debugging performace

---

Cargo.lock
Cargo.toml
Makefile.toml
cli/golem-cli/Cargo.toml
cli/golem-cli/src/command.rs
cli/golem-cli/src/command_handler/api/definition.rs
cli/golem-cli/src/model/app.rs
cli/golem-cli/src/model/app_raw.rs
cli/golem-cli/src/model/deploy_diff/api_definition.rs
cli/golem-cli/src/model/mod.rs
cli/golem-cli/src/model/text/api_definition.rs
cli/golem/Cargo.toml

This adds `swagger` and `export` commands to cli, api definition
swagger
```bash
golem api definition swagger [OPTIONS] --id <ID> --version <VERSION>
-i, --id <ID>
Api definition id
-V, --version <VERSION>
Version of the api definition
-P, --port <PORT>
Port to open Swagger UI on (defaults to 9007) [default: 9007]
```
export 
```bash
golem api definition export [OPTIONS] --id <ID> --version <VERSION>
-i, --id <ID>
Api definition id
-V, --version <VERSION>
Version of the api definition
--def-format <def-format>
Output format (json or yaml) [default: yaml]
-o, --output-name <OUTPUT_NAME>
Custom output file name (without extension)
```

Export and swagger commands in golem-cli

---

Cargo.lock
Cargo.toml
cli/golem-cli/src/model/agent/moonbit.rs
cli/golem-cli/src/model/agent/test.rs
cli/golem-cli/src/model/agent/wit.rs

Resolves #1919 
(Partially) resolves #1992 
Note that the ` [E2000] Warning (Alert deprecated): Use `Int::unsafe_to_char` instead, and use `Int::to_char` for safe conversion` warning does not seem to be removable.

Support wit/moonbit keywords in agent type definitions

---

.github/workflows/ci.yaml

To avoid limitations on the number of sticky disks (as each docker step is using one)
https://docs.blacksmith.sh/blacksmith-caching/dependencies-sticky-disks#how-it-works

Split docker publish steps in ci

---

Cargo.lock
Cargo.toml
Makefile.toml
cli/golem-cli/src/model/agent/moonbit.rs
cli/golem-cli/src/model/agent/wit.rs
cli/golem-cli/wit/deps/logging/logging.wit
golem-common/src/model/agent/mod.rs
golem-common/src/model/mod.rs
golem-worker-executor/src/services/worker_event.rs

Resolves #2041 
Also adds the wasi:logging messages to the invocation failure above warning level (previously it only contained the captured `stderr`)

Removed result<_, agent-error> from agent wrapper interfaces

---

cli/golem-templates/templates/ts/ts-app-component-websearch-summary-example/components-ts/component-name/golem.yaml

- Fix the HTTP API name
- Moved the API def to top to be aligned with the other two templates

Fix websearch-summary-example template
